/*- Lista contas contábeis dos eventos do Labore -*/

SELECT DISTINCT
	CODIGO, PEVENTO.DESCRICAO, CONTACREDITO GRPCRED, CC.CONTASALDUS AS CCREDSALDUS, CS1.DESCRICAO DSCRED, CS1.REDUZIDO REDCRED,
	CONTADEBITO GRPDEB, CD.CONTASALDUS AS CDEBSALDUS, CS2.DESCRICAO DESDEB, CS2.REDUZIDO REDDEB, 
	CC.INTEGRCFUNC AS TPINTCRED, CD.INTEGRCFUNC AS TPINCDEB
FROM PEVENTO
LEFT JOIN PCONTAS CC ON CC.GRPCONTA = PEVENTO.CONTACREDITO
LEFT JOIN PCONTAS CD ON CD.GRPCONTA = PEVENTO.CONTADEBITO 
LEFT JOIN CCONTA CS1 ON CS1.CODCONTA = CC.CONTASALDUS
LEFT JOIN CCONTA CS2 ON CS2.CODCONTA = CD.CONTASALDUS


