/* Localiza Alunos e Pais por Nacionalidade */

SELECT 
	EALUNOS.NOME, PCODNACAO.DESCRICAO, 
	EACOMPL.A_NACIONAL1, EACOMPL.A_NACIONAL2, EACOMPL.A_NACIONAL3,
	CASE 
		WHEN EACOMPL.A_PESSOA1 = 'PAI' THEN (SELECT NOME FROM PPESSOA WHERE CODIGO = EALUNOS.PAI)
		WHEN EACOMPL.A_PESSOA1 = 'MÃE' THEN (SELECT NOME FROM PPESSOA WHERE CODIGO = EALUNOS.MAE)
		WHEN EACOMPL.A_PESSOA1 = 'RESPONSÁVEL ACADÊMICO' THEN (SELECT NOME FROM PPESSOA WHERE CODIGO = EALUNOS.RESPACAD)
	END AS PAI, 
	CASE 
		WHEN EACOMPL.A_PESSOA1 = 'PAI' THEN (SELECT EMAIL FROM PPESSOA WHERE CODIGO = EALUNOS.PAI)
		WHEN EACOMPL.A_PESSOA1 = 'MÃE' THEN (SELECT EMAIL FROM PPESSOA WHERE CODIGO = EALUNOS.MAE)
		WHEN EACOMPL.A_PESSOA1 = 'RESPONSÁVEL ACADÊMICO' THEN (SELECT EMAIL FROM PPESSOA WHERE CODIGO = EALUNOS.RESPACAD)
	END AS EMAILPAI, 
	CASE 
		WHEN EACOMPL.A_PESSOA1 = 'PAI' THEN (SELECT TELALUNO + '/' + TELEFONE1 + '/' +  TELEFONE2 + '/' +  TELEFONE3  FROM PPESSOA WHERE CODIGO = EALUNOS.PAI)
		WHEN EACOMPL.A_PESSOA1 = 'MÃE' THEN (SELECT TELALUNO + '/' + TELEFONE1 + '/' +  TELEFONE2 + '/' +  TELEFONE3  FROM PPESSOA WHERE CODIGO = EALUNOS.MAE)
		WHEN EACOMPL.A_PESSOA1 = 'RESPONSÁVEL ACADÊMICO' THEN (SELECT TELALUNO + '/' + TELEFONE1 + '/' +  TELEFONE2 + '/' +  TELEFONE3  FROM PPESSOA WHERE CODIGO = EALUNOS.RESPACAD)
	END AS FONEPAI, 
	CASE 
		WHEN EACOMPL.A_PESSOA2 = 'PAI' THEN (SELECT NOME FROM PPESSOA WHERE CODIGO = EALUNOS.PAI)
		WHEN EACOMPL.A_PESSOA2 = 'MÃE' THEN (SELECT NOME FROM PPESSOA WHERE CODIGO = EALUNOS.MAE)
		WHEN EACOMPL.A_PESSOA2 = 'RESPONSÁVEL ACADÊMICO' THEN (SELECT NOME FROM PPESSOA WHERE CODIGO = EALUNOS.RESPACAD)
	END AS MAE, 	
	CASE 
		WHEN EACOMPL.A_PESSOA2 = 'PAI' THEN (SELECT EMAIL FROM PPESSOA WHERE CODIGO = EALUNOS.PAI)
		WHEN EACOMPL.A_PESSOA2 = 'MÃE' THEN (SELECT EMAIL FROM PPESSOA WHERE CODIGO = EALUNOS.MAE)
		WHEN EACOMPL.A_PESSOA2 = 'RESPONSÁVEL ACADÊMICO' THEN (SELECT EMAIL FROM PPESSOA WHERE CODIGO = EALUNOS.RESPACAD)
	END AS EMAILMAE, 
	CASE 
		WHEN EACOMPL.A_PESSOA2 = 'PAI' THEN (SELECT TELALUNO + '/' + TELEFONE1 + '/' +  TELEFONE2 + '/' +  TELEFONE3  FROM PPESSOA WHERE CODIGO = EALUNOS.PAI)
		WHEN EACOMPL.A_PESSOA2 = 'MÃE' THEN (SELECT TELALUNO + '/' + TELEFONE1 + '/' +  TELEFONE2 + '/' +  TELEFONE3  FROM PPESSOA WHERE CODIGO = EALUNOS.MAE)
		WHEN EACOMPL.A_PESSOA2 = 'RESPONSÁVEL ACADÊMICO' THEN (SELECT TELALUNO + '/' + TELEFONE1 + '/' +  TELEFONE2 + '/' +  TELEFONE3  FROM PPESSOA WHERE CODIGO = EALUNOS.RESPACAD)
	END AS FONEMAE
	--P1.NOME, P2.NOME, * 
FROM EALUNOS
	INNER JOIN UMATRICPL ON UMATRICPL.MATALUNO = EALUNOS.MATRICULA
	INNER JOIN EACOMPL ON EACOMPL.MATRICULA = EALUNOS.MATRICULA
	INNER JOIN PCODNACAO ON PCODNACAO.CODCLIENTE = EALUNOS.NACIONAL
	INNER JOIN PPESSOA P1 ON P1.CODIGO = EALUNOS.PAI
	INNER JOIN PPESSOA P2 ON P2.CODIGO = EALUNOS.MAE
WHERE 
	UMATRICPL.PERLETIVO = '17/18'
	AND 
		(PCODNACAO.DESCRICAO LIKE 'FRANC%' OR EACOMPL.A_NACIONAL1 = 'FRENCH'
		 OR EACOMPL.A_NACIONAL2 = 'FRENCH' OR EACOMPL.A_NACIONAL3 = 'FRENCH')