select 
	IOCORRENCIA.DATA,
	
	IPATRIMONIO.DESCRICAO,
	case when IOCORRENCIA.TIPO = 99 then 'Baixa Total' end as TipoBaixa,
	IMOTIVOBAIXA.DESCRICAO,
	IOCORRENCIA.VALOROCORRENCIA,
	IGRUPOPATRIMONIO.DESCRICAO
from 
	IOCORRENCIA
inner join IPATRIMONIO (Nolock) on (IOCORRENCIA.IDPATRIMONIOMOEDAORIGEM = IPATRIMONIO.IDPATRIMONIO)
inner join IMOTIVOBAIXA (Nolock) on (IMOTIVOBAIXA.CODMOTIVOBAIXA = IOCORRENCIA.IDMOTIVOBAIXA)
inner join IGRUPOPATRIMONIO (Nolock) on (IPATRIMONIO.IDGRUPOPATRIMONIO = IGRUPOPATRIMONIO.IDGRUPOPATRIMONIO)
where 
	DATA between '08/01/2013' and '07/31/2014'
order by DATA