Select 
	CODIGOBARRA,
	DESCRICAO,
	DATAAQUISICAO,
	ATIVO,
	AQUISICAO,
	CASE 
		WHEN ATIVO = 0 THEN AQUISICAO
		ELSE (SELECT ICALCULORAZAO.DEPRECIACAOACUMULADA from ICALCULORAZAO WHERE ICALCULORAZAO.DATA between '07/01/2014' and '07/31/2014' AND ICALCULORAZAO.IDCALCULOPATRIMONIO = (select ICALCULOPATRIMONIO.IDCALCULOPATRIMONIO from ICALCULOPATRIMONIO where ICALCULOPATRIMONIO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO))
	END AS DEPRECIACAOACUMULADA,
	(SELECT ITAXADEPRECIACAO.VALOR from ITAXADEPRECIACAO WHERE ITAXADEPRECIACAO.IDCALCULOPATRIMONIO = (select ICALCULOPATRIMONIO.IDCALCULOPATRIMONIO from ICALCULOPATRIMONIO where ICALCULOPATRIMONIO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO)) AS TX_DEP
from 
	IPATRIMONIO
where 
	DATAAQUISICAO is not null







