/*
	EXTRATO PTA
*/

Select 
IDLAN,
DATABAIXA,
(SELECT NOMEFANTASIA FROM FCFO WHERE FCFO.CODCFO = FLAN.CODCFO) AS FORNECEDOR,
HISTORICO, VALORBAIXADO + isnull(VALORADIANTAMENTO,0) + Case when idlan = 198843 then VALORADIANTAMENTO * - 1 else 0 end from FLAN where
CODTDO in (Select CODTDO from FTDOCONT where CODCONTA = (Select CODCONTA from CCONTA where REDUZIDO = 176 and CCONTA.CODCONTA NOT LIKE '1.1.03%'))
and DATABAIXA between '08-01-2016' and '12-05-2016'
and PAGREC = 1

UNION

Select
IDLAN, 
DATABAIXA,
(SELECT NOMEFANTASIA FROM FCFO WHERE FCFO.CODCFO = FLAN.CODCFO) AS FORNECEDOR,
HISTORICO, (VALORBAIXADO + isnull(VALORADIANTAMENTO,0)) * -1 
+ case when IDLAN = 323853 then VALORORIGINAL * -1 
when IDLAN = 323854 then VALORORIGINAL * -1
else 0 end 
from FLAN where
CODTDO in (Select CODTDO from FTDOCONT where CODCONTA = (Select CODCONTA from CCONTA where REDUZIDO = 176 and CCONTA.CODCONTA NOT LIKE '1.1.03%'))
and DATABAIXA between '08-01-2016' and '12-05-2016'
and PAGREC = 2
ORDER BY DATABAIXA