Select 
	CAST(DATEPART(MM, FLAN.DATAVENCIMENTO)AS VARCHAR) + '/' + 
	CAST(DATEPART(YYYY, FLAN.DATAVENCIMENTO)AS VARCHAR),
	SUM(VALORBAIXADO) AS VALOR
from FLAN
Where
	FLAN.CODCFO = 'F00044'
AND DATEPART(YYYY, FLAN.DATAVENCIMENTO) = 2009
GROUP BY 
	DATEPART(MM, FLAN.DATAVENCIMENTO), 
	DATEPART(YYYY, FLAN.DATAVENCIMENTO)

