
Select 
	FLAN.DATAVENCIMENTO,
	FLAN.CODCFO, 
	CONVERT(nvarchar(30), FLAN.DATAVENCIMENTO, 103) + ' - ' +
	(Select NOME from FCFO where FCFO.CODCFO = FLAN.CODCFO),
	FLAN.VALORBAIXADO 
from FLAN
where FLAN.CODTDO = '000044'
and FLAN.DATAVENCIMENTO between '03/01/2013' and '03/31/2013'
and FLAN.TIPOCONTABILLAN != 0
