SELECT FLAN.IDLAN, * FROM FLAN, FTDO
WHERE FLAN.CODCOLIGADA = FTDO.CODCOLIGADA
AND FLAN.CODTDO = FTDO.CODTDO
AND FLAN.CODCOLIGADA = 1
AND FTDO.EDEVOLUCAO = 2
AND FLAN.IDLAN NOT IN (SELECT IDLAN FROM FRELLAN WHERE CODCOLIGADA = 1 AND (TIPOREL=22 or TIPOREL=2))
AND FLAN.IDLAN NOT IN (SELECT IDLANREL FROM FRELLAN WHERE CODCOLIGADA = 1 AND (TIPOREL=22 or TIPOREL=2))