
SELECT  '1 - Adto Sem Vinculo',
	FLAN.CODCFO,
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, 
    FLAN.HISTORICO,
	FLAN.DATABAIXA,
	NULL AS DTBXADTOVINCULO,
	sum(VALORORIGINAL) as VlrAdto, 
    FLAN.IDLAN, IDLAN
FROM 
	FLAN 
where	FLAN.CODCOLIGADA = 1 
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND not EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 2 AND R.CODCOLIGADA = 1) 
AND CODTDO = '000044' /* IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2)*/ 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0
AND DATAVENCIMENTO >= '01/01/2009' and (DATABAIXA <='04/30/2013')
Group by FLAN.CODCFO,  CODTDO,FLAN.IDLAN, FLAN.HISTORICO, FLAN.DATABAIXA, FLAN.DATABAIXA

union

Select '2 - Adto Vinculados e Baixados que Geraram Baixa Parcial no adto',
	FLAN.CODCFO, 
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, 
	(SELECT HISTORICO FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) as Hist,
	flan.DATABAIXA,
	(SELECT DATABAIXA FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) AS DTBXADTOVINCULO,
	(SELECT VALORORIGINAL FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) -
		Case 
			when Flan.CODCFO = 'C00750' and FLAN.IDLAN = 182468 then 931.50 
		else 
			0
		end
	AS vlrbaixadoADTO, 
	FLAN.IDLAN, FRELLAN.IDLANREL
from 
	FLAN
Inner Join FRELLAN (NoLock) on (FRELLAN.IDLAN = FLAN.IDLAN)
where
	FLAN.CODCOLIGADA  = 1 
AND FRELLAN.TIPOREL = 11
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODTDO NOT IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
AND (SELECT FLAN2.CODTDO FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
-- and CODCFO = 'c00846'
AND STATUSLAN = 1 
AND DATAVENCIMENTO >= '01/01/2009' 
AND DATABAIXA >='04/01/2013'
AND DATABAIXA <='04/30/2013'
AND FLAN.IDLAN <> 199681


union

Select '3 - Adto Vinculados e NÃO Baixados',
	FLAN.CODCFO,  
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, 
	(SELECT HISTORICO FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) as Hist,
	FLAN.DATABAIXA,
	(SELECT FLAN2.DATABAIXA     FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) AS DataBaixaDoADTO,
	(SELECT FLAN2.VALORORIGINAL FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) AS vlrbaixadoADTO,
--	(SELECT FLAN2.DATAVENCIMENTO FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) as datavencimentoDOlancamentoquerecebeuovinculo,
	FLAN.IDLAN as idlandaflan, FRELLAN.IDLAN as idlandafrellan
from 
	FLAN
Inner Join FRELLAN (NoLock) on (FRELLAN.IDLANREL = FLAN.IDLAN)
where
	FLAN.CODCOLIGADA  = 1 
AND FRELLAN.TIPOREL = 2
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND (SELECT FLAN2.CODTDO FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLANREL) IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
--and CODCFO = 'c00933'
AND FLAN.STATUSLAN = 1 
AND (SELECT STATUSLAN FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) = 0
AND FLAN.DATAVENCIMENTO >= '01/01/2009' 
AND	FLAN.DATABAIXA <= '04/30/2013'
AND NOT EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 11 AND R.CODCOLIGADA = 1) 


UNION

Select '4 - Adto Vinculados e Baixados que NÃO Geraram Baixa Parcial no adto',
	FLAN.CODCFO, 
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, 
     FLAN.HISTORICO,
	FLAN.DATABAIXA,
	(Select FLAN2.DATABAIXA from FLAN FLAN2 where FLAN2.IDLAN = FRELLAN.IDLAN) AS DTBXADTO,
	 sum(VALORORIGINAL) as VlrAdto, 
     FLAN.IDLAN,
     FRELLAN.IDLAN   
FROM 
	FLAN 
Inner Join FRELLAN (NoLock) on (FRELLAN.IDLANREL = FLAN.IDLAN)
where	
	FLAN.CODCOLIGADA = 1 
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND STATUSLAN = 1 
AND EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 2 AND R.CODCOLIGADA = 1) 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0
AND DATAVENCIMENTO >= '01/01/2009' 
AND CODTDO = '000044' /* IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2)*/ 
and (Select FLAN2.DATABAIXA from FLAN FLAN2 where FLAN2.IDLAN = FRELLAN.IDLAN) >= '04/30/2013' 
and FLAN.DATABAIXA <= '04/30/2013'
AND NOT EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 11 AND R.CODCOLIGADA = 1) 
AND (Select FLAN2.DATABAIXA from FLAN FLAN2 where FLAN2.IDLAN = FRELLAN.IDLAN) is not null
Group by FLAN.CODCFO, FLAN.IDLAN, FLAN.HISTORICO, FLAN.DATABAIXA, FLAN.DATABAIXA, FRELLAN.IDLAN

UNION

SELECT '5 - Adto Baixados antes de FEV/2013',
	FLAN.CODCFO, 
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, FLAN.HISTORICO,
	flan.DATABAIXA,
	(SELECT DATABAIXA FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) AS DTBXADTO,
	sum(VALORORIGINAL) as VlrAdto, FLAN.IDLAN, FRELLAN.IDLAN
FROM 
	FLAN 
INNER JOIN FRELLAN (NoLock) ON (FRELLAN.IDLANREL = FLAN.IDLAN or FRELLAN.IDLAN = FLAN.IDLAN)
WHERE
	FLAN.CODCOLIGADA  = 1 
AND FRELLAN.TIPOREL = 2
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND STATUSLAN = 1 
AND CODTDO  IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0
AND DATAVENCIMENTO >= '01/01/2009' 
and DATABAIXA <= '02/28/2013' 
and (SELECT DATABAIXA FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) >= case when '03/01/2013' = '03/01/2013' then '03/31/2013' else '04/30/2013' end
AND FLAN.IDLAN = (184883)
Group by FLAN.CODCFO, FLAN.IDLAN, FLAN.HISTORICO, FLAN.DATABAIXA,  FRELLAN.IDLAN, FLAN.DATABAIXA, FRELLAN.IDLANREL

order by Cliente, databaixa
--select * from FRELLAN where IDLAN = 193690