/* ADTO Ja vinculados */
SELECT 
	CODCFO, 
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, FLAN.HISTORICO,
	flan.DATABAIXA,
	(SELECT DATABAIXA FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) AS DTBXADTO,
	sum(VALORORIGINAL) as VlrAdto, FLAN.IDLAN
FROM 
	FLAN 
INNER JOIN FRELLAN (NoLock) ON (FRELLAN.IDLANREL = FLAN.IDLAN or FRELLAN.IDLAN = FLAN.IDLAN)
WHERE
	FLAN.CODCOLIGADA  = 1 
AND FRELLAN.TIPOREL = 2
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND STATUSLAN = 1 
--and CODCFO = 'C00646'
AND CODTDO  IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0
AND DATAVENCIMENTO >= '01/01/2009' 
and (DATABAIXA <= '03/31/2013' or DATABAIXA is null)
AND ((SELECT DATABAIXA FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) BETWEEN '04/01/2013' AND '04/30/2013'
OR	 (SELECT DATABAIXA FROM FLAN FLAN2 WHERE FLAN2.IDLAN = FRELLAN.IDLAN) is null)
Group by CODCFO, FLAN.IDLAN, FLAN.HISTORICO, FLAN.DATABAIXA,  FRELLAN.IDLAN, DATAVENCIMENTO


/* SEM VINCULOS */ 

union

SELECT 
	CODCFO, 
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = FLan.CODCFO) as Cliente, FLAN.HISTORICO,
	flan.DATABAIXA,
	Null AS DTBXADTO,
	sum(VALORORIGINAL) as VlrAdto, IDLAN
FROM 
	FLAN 
where	CODCOLIGADA = 1 
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND STATUSLAN = 1 
AND NOT EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 2 AND R.CODCOLIGADA = 1) 
AND CODTDO = '000044' -- IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0
AND DATAVENCIMENTO >= '01/01/2009' and (DATABAIXA <= '03/31/2013' or DATABAIXA is null)
Group by CODCFO, IDLAN, FLAN.HISTORICO, FLAN.DATABAIXA, flan.DATABAIXA
order by flan.DATABAIXA

/* MANUTENCAO 
SELECT * FROM FRELLAN WHERE IDLANREL = 198395 and TIPOREL = 2

insert into FRELLAN(CODCOLIGADA,IDLAN,IDLANREL, TIPOREL) values  ('1', 198395, 198395, 2)
*/

/*
-- Detalhe
SELECT 
	IDLAN, VALORORIGINAL, DATAVENCIMENTO, DATABAIXA, CODTDO , HISTORICO
FROM 
	FLAN 
WHERE 
	CODCOLIGADA = 1 
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND CODCFO = 'C00354' 
AND STATUSLAN = 1 
AND NOT EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 2 AND R.CODCOLIGADA = 1) 
AND CODTDO = '000044' -- IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0



Select 
	(Select CODCFO from FCFO where FCFO.CODCFO = EALUNOS.RESPONS) as CodCli,
	(Select NOMEFANTASIA from FCFO where FCFO.CODCFO = EALUNOS.RESPONS) as Cliente,
	MATRICULA,
	NOME,
	(Select Descricao from USITMAT where CodSitMat =
	(Select top 1 UALUCURSO.STATUS from UALUCURSO where UaluCurso.MATALUNO = Ealunos.MATRICULA and Ualucurso.status != 10 order by CodCur desc, Codper desc)) as StatusAluno
from 
	EALUNOS 
where EALUNOS.RESPONS
in
(SELECT 
	CODCFO
FROM 
	FLAN 
WHERE 
	CODCOLIGADA = 1 
AND NFOUDUP <> 1 
AND (NUMBLOQUEIOS = 0 OR NUMBLOQUEIOS IS NULL) 
AND (BAIXAAUTORIZADA IS NULL OR BAIXAAUTORIZADA <> 0) 
AND PAGREC = 1 
AND CODCOLCFO = 1 
AND STATUSLAN = 1 
AND NOT EXISTS (SELECT * FROM FRELLAN R (NOLOCK) WHERE (FLAN.IDLAN = R.IDLAN OR FLAN.IDLAN = R.IDLANREL) AND R.TIPOREL = 2 AND R.CODCOLIGADA = 1) 
AND CODTDO = '000044' -- IN (SELECT CODTDO FROM FTDO WHERE CODCOLIGADA = 1 AND EDEVOLUCAO = 2) 
AND VALORADIANTAMENTO = 0 AND VALORDEVOLUCAO = 0
AND DATAVENCIMENTO >= '08/01/2009'
Group by CODCFO)
Order by Cliente

*/