select *
from 	FXCX
Where 	CodCXA = '001'
and	data = '2006-02-01'

SELECT 
 	FXCX.VALOR, 
	FXCXCONT.CODCONTA
FROM 
 	FXCX
 	INNER JOIN FXCXCONT ON (FXCXCONT.IDXCX = FXCX.IDXCX)
WHERE  FXCXCONT.TIPO = 1 
       AND FXCX.VALOR > 0
