

SELECT TOP 1
	(SELECT COUNT(DISTINCT UMATALUN.MATALUNO) FROM UMATALUN WHERE CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE MATERIA LIKE '%ESL%') AND PERLETIVO = '14/15') AS TOTALESL,
	(SELECT COUNT(DISTINCT UMATALUN.MATALUNO) FROM UMATALUN WHERE CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE MATERIA LIKE '%ESL%') AND PERLETIVO = '14/15' AND CODCUR = 2 AND CODPER = 1) AS TOTALELEM ,
	(SELECT COUNT(DISTINCT UMATALUN.MATALUNO) FROM UMATALUN WHERE CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE MATERIA LIKE '%ESL%') AND PERLETIVO = '14/15' AND (CODCUR = 2 AND CODPER = 2 OR CODCUR = 3)) AS TOTALSEC	
FROM 
	GLOGIN 


SELECT 
	DISTINCT UMATALUN.MATALUNO AS '14/15',
	(SELECT TOP 1 'ESL' FROM UMATALUN EMT WHERE EMT.CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE MATERIA LIKE '%ESL%') AND EMT.MATALUNO = UMATALUN.MATALUNO AND EMT.PERLETIVO = '15/16' AND CODCUR = 2 AND CODPER = 1) AS '15/16 ELEM',
	(SELECT TOP 1 'ESL' FROM UMATALUN EMT WHERE EMT.CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE MATERIA LIKE '%ESL%') AND EMT.MATALUNO = UMATALUN.MATALUNO AND EMT.PERLETIVO = '15/16' AND (CODCUR = 2 AND CODPER = 2 OR CODCUR = 3)) AS '15/16 SEC'
FROM 
	UMATALUN 
WHERE 
	CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE MATERIA LIKE '%ESL%') 
AND PERLETIVO = '14/15'