Select Distinct
	(Select top 1 case when UMatricpl.CodCur = '1' then UMATALUN.CODTUR else 'Grade ' + UMATALUN.CODTUR end as Turma from UMatAlun where UMatAlun.Status in ('01', '07','18') and UMatAlun.MatAluno = EAlunos.Matricula and UMatAlun.Perletivo = Umatricpl.Perletivo and UMatricPL.Status in('01','07','18') Group by UMatAlun.CodTur Order by count(UMatAlun.CodTur) desc) as Grade_Level,
	
 	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and UMA.CodTur = UMatAlun.CodTur) as TotalNumber,
 	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and (Ealunos.TipoAluno = 1 or Ealunos.TipoAluno is null) and UMA.CodTur = UMatAlun.CodTur) as LocalStd,
  	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and Ealunos.TipoAluno in (3,4) and UMA.CodTur = UMatAlun.CodTur) as CorpStd,
  	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and Ealunos.TipoAluno = 2 and UMA.CodTur = UMatAlun.CodTur) as TempStd,
  	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and Ealunos.TipoAluno = 5 and UMA.CodTur = UMatAlun.CodTur) as StaffStd,

 	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join EACompl (NoLock) on (EACompl.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and Ealunos.TipoAluno in (3,4) and ((A_DataSaidaISC is not null and A_ReturnedToISC is null) or  A_LeftISC_2 is not null) and UMA.CodTur = UMatAlun.CodTur) as PendLeavingCorp,
 	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('18') and Ealunos.TipoAluno in (3,4) and UMA.CodTur = UMatAlun.CodTur) as PendEnterCorp,
 	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join EACompl (NoLock) on (EACompl.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('01','07') and Ealunos.TipoAluno in (1,2) and ((A_DataSaidaISC is not null and A_ReturnedToISC is null) or  A_LeftISC_2 is not null) and UMA.CodTur = UMatAlun.CodTur) as PendLeavingOthers,
  	(select count(distinct UMPL.MatAluno)  from Umatricpl UMPL Inner join Ealunos (NoLock) on (Ealunos.Matricula = UMPL.MatAluno) Inner Join UMatAlun UMA (NoLock) on (UMA.PerLetivo = UMPL.PerLetivo and UMA.MatAluno = UMPL.MatAluno) where UMPL.Perletivo = Umatricpl.Perletivo and UMPL.Codcur = Umatricpl.Codcur and UMPL.Codper = Umatricpl.Codper and UMPL.Periodo = UMatricpl.Periodo and UMPL.status in ('18') and (Ealunos.TipoAluno not in (3,4) or Ealunos.TipoAluno is null) and UMA.CodTur = UMatAlun.CodTur) as PendEnterOthers,
 
 	UMatricpl.CodCur, UMatricpl.CodPer , UMatricpl.Periodo
 --	'1' as Quebra$$,
  --      (Select distinct UMT.MaxAlunos from UMatTurma UMT where UMT.CodPerlet = Umatricpl.Perletivo and UMatAlun.CodTur = UMT.CodTur),
   --     Case When Umatricpl.CodCur = 2 and Umatricpl.CodPer = 1 and Umatricpl.Periodo in (1,2,3) then 28 else
   --     (Select distinct UMT.MaxAlunos from UMatTurma UMT where UMT.CodPerlet = Umatricpl.Perletivo and UMatAlun.CodTur = UMT.CodTur) + 5
   --     end
from 
        Umatricpl
	inner Join Ealunos (NoLock) on (EAlunos.Matricula = UMatricPL.MatAluno)
	inner Join UMatAlun (NoLock) on (UMatAlun.PerLetivo = Umatricpl.PerLetivo and UMatAlun.MatAluno = Umatricpl.MatAluno)
Where 	
        Umatricpl.Perletivo ='10/11'
 	and UMatricPL.Status in('01','07','18')  
Order By UMatricpl.CodCur, UMatricpl.CodPer, UMatricpl.Periodo