/* Balancete por Período e/ou Centro de Custo */

DECLARE @Datainicio as date
DECLARE @DataFinal as date
DECLARE @CodFilial as int
--DECLARE @CentroCusto as varchar

set @Datainicio = '08-01-2016'
set @DataFinal = '07-31-2017'
set @CodFilial = 1
--set @CentroCusto = '11FF0000'

SELECT C3.CODCOLIGADA, C3.CODCONTA, C3.DESCRICAO,
       ISNULL(SUM(BALANCETE.SALDANT),0) AS SALDANT,
       ISNULL(SUM(BALANCETE.DEBITO),0) AS DEBITO,
       ISNULL(SUM(BALANCETE.CREDITO),0) AS CREDITO,
       ISNULL(SUM(BALANCETE.SALDO),0) AS SALDO
FROM CCONTA C3 (NOLOCK),
 (SELECT CODCOLIGADA,CODCONTA,DESCRICAO,(ISNULL(DEBANT,0)-ISNULL(CREDANT,0)) AS SALDANT,DEBITO,CREDITO,(ISNULL(DEBANT,0)-ISNULL(CREDANT,0)+ISNULL(DEBITO,0)-ISNULL(CREDITO,0)) AS SALDO,ANALITICA
  FROM

    (SELECT  C2.CODCOLIGADA,C2.CODCONTA,C2.DESCRICAO,C2.ANALITICA,
         (select SUM((CLANCA.VALOR )) 
          from CLANCA (NOLOCK)
          where CLANCA.DEBITO = C2.CODCONTA AND CLANCA.DATA < @DataInicio AND CLANCA.CODFILIAL = @CodFilial ) AS DEBANT,
         (select SUM((CLANCA.VALOR )) 
          from CLANCA (NOLOCK)
          where CLANCA.CREDITO = C2.CODCONTA AND CLANCA.DATA < @DataInicio AND CLANCA.CODFILIAL = @CodFilial ) AS CREDANT,
         (select SUM((CLANCA.VALOR ))
          from CLANCA (NOLOCK)
          where CLANCA.DEBITO = C2.CODCONTA AND CLANCA.DATA >= @DataInicio AND CLANCA.DATA <= @DataFinal AND CLANCA.CODFILIAL = @CodFilial )DEBITO,
         (select SUM((CLANCA.VALOR )) 
          from CLANCA (NOLOCK) 
          where CLANCA.CREDITO = C2.CODCONTA AND CLANCA.DATA >= @DataInicio AND CLANCA.DATA <= @DataFinal AND CLANCA.CODFILIAL = @CodFilial )CREDITO    
     FROM CCONTA C2 (NOLOCK)) X1

  WHERE X1.ANALITICA=1) AS BALANCETE
WHERE BALANCETE.CODCONTA LIKE C3.CODCONTA+'%'
GROUP BY C3.CODCOLIGADA, C3.CODCONTA, C3.DESCRICAO
ORDER BY C3.CODCONTA  