INSERT INTO  EMatricpl
	(CODCOLIGADA, CODFILIAL, MATALUNO, PERLETIVO, 
	CODCUR, CODPER, CODTUN, CODTUR, SITMAT, 
	DATAMAT, DATAALT, USUARIO, DTREG)
(Select 
	CODCOLIGADA,
	CODFILIAL,
	MATALUNO,
	PERLETIVO,
	CODCUR,
	PERIODO,
	CASE
		WHEN CODCUR = 1 THEN '1'
		WHEN CODCUR = 2 AND PERIODO <= 5 THEN '2'
		WHEN CODCUR = 2 AND PERIODO >= 6 THEN '3'
		WHEN CODCUR = 3 THEN '3'
	END AS CODTUN,
    (Select top 1 UMATALUN.CODTUR from UMatAlun where UMatAlun.MatAluno = UMATRICPL.MatALUNO and UMatAlun.Perletivo ='07/08' Group by UMatAlun.CodTur Order by count(UMatAlun.CodTur) desc) as CODTUR,
	STATUS,
	DATAMAT,
	DATAALT,
	USUARIO,
	GETDATE()
from UMatricpl where perletivo = '07/08' AND STATUS NOT IN ('02','09'))

