/*
SELECT DISTINCT
	Case When ZFamilia.lingua = 'Portuguese' then 'Família ' + RTrim(ZFamilia.Nome)
	Else RTrim(ZFamilia.Nome) + ' Family' End,
	ZFamilia.Pessoa1,
	ZFamilia.Pessoa2,
	ZFamilia.Nome, EACompl.A_NOMEREDUZIDO, Eacompl.Matricula
FROM
	ZFAMILIA
	INNER JOIN EALUNOS ON (ZFAMILIA.MATRICULA = EALUNOS.MATRICULA)
	INNER JOIN UMATRICPL ON (EALUNOS.MATRICULA = UMATRICPL.MATALUNO and UMATRICPL.PERLETIVO ='06/07')--:ESPELHO#1)
	INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
WHERE
	UMATRICPL.PERLETIVO ='06/07'--:ESPELHO#1
	AND UMATRICPL.PERIODO >='9'--:ESPELHO#3
	AND UMATRICPL.PERIODO <='12'--:ESPELHO#4
     AND UMATRICPL.CODCUR >= '2'
	AND UMATRICPL.STATUS IN ('01', '07')
Order by  EACompl.A_NOMEREDUZIDO
*/


SELECT TOP 1
	EALUNOS.NOME, '(' + UMATALUN.CODTUR + ')', EALUNOS.DTNASC,  UMATALUN.CODTUR
FROM
	ZFAMILIA
	INNER JOIN EALUNOS ON (ZFAMILIA.MATRICULA = EALUNOS.MATRICULA)
	INNER JOIN UMATRICPL ON (EALUNOS.MATRICULA = UMATRICPL.MATALUNO AND UMATRICPL.PERLETIVO ='06/07')--:ESPELHO#1)
	INNER JOIN UMATALUN ON (UMATRICPL.MATALUNO = UMATALUN.MATALUNO AND UMATALUN.PERLETIVO='06/07')--:ESPELHO#1)
WHERE
	ZFAMILIA.PESSOA1 ='218' --:ESPELHO#2
	AND ZFAMILIA.PESSOA2 ='223'--:ESPELHO#5
	AND UMATRICPL.PERLETIVO ='06/07'--:ESPELHO#1
	AND UMATRICPL.PERIODO >='9'--:ESPELHO#3
	AND UMATRICPL.PERIODO <='10'--:ESPELHO#4
	AND UMATRICPL.STATUS IN ('01', '07')
Order by 
	EALUNOS.DTNASC Desc, UMATALUN.CODTUR