SELECT 
	EPROFES.CHAPA,
       	LEFT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))),
	LEN(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))))-2),
	RIGHT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))),2),
       	GCCUSTO.CODCCUSTO
FROM 
       EPROFES, 
       UPROFMATTURMA,
       UGRADE,
       GCCUSTO
WHERE
       UPROFMATTURMA.TIPOPROF = 'T'
AND    UPROFMATTURMA.CODPERLET='05/06'
AND    EPROFES.CODPROF = UPROFMATTURMA.CODPROF
AND    UGRADE.CODMAT = UPROFMATTURMA.CODMAT
AND    UGRADE.CODMATG = GCCUSTO.CODREDUZIDO
AND    UPROFMATTURMA.NAULASSEMPROF <> 0
GROUP BY 
       EPROFES.CHAPA,
       GCCUSTO.CODCCUSTO
ORDER BY
       EPROFES.CHAPA
