SELECT DISTINCT
	EAcompl.A_NomeReduzido, '(' + UMATALUN.CODTUR + ')', EALUNOS.DTNASC
FROM
	ZFAMILIA
	INNER JOIN EALUNOS ON (ZFAMILIA.MATRICULA = EALUNOS.MATRICULA)
	INNER JOIN EACOMPL ON (ZFAMILIA.MATRICULA = EACOMPL.MATRICULA)
	INNER JOIN UMATRICPL ON (EALUNOS.MATRICULA = UMATRICPL.MATALUNO)
	INNER JOIN UMATALUN ON (UMATRICPL.MATALUNO = UMATALUN.MATALUNO)
WHERE
	ZFAMILIA.PESSOA1 ='147'
	AND ZFAMILIA.PESSOA2 ='148'
	AND UMATRICPL.PERLETIVO ='06/07'
	And UMATALUN.PERLETIVO = '06/07'
	AND UMATRICPL.STATUS IN ('01', '07')
Order by 
	EALUNOS.DTNASC Desc