SELECT
	ZFAMILIA.MATRICULA, EALUNOS.NOME, EALUNOS.DTNASC,
	Case 
	When EAcompl.A_Nacional3 is null and EAcompl.A_Nacional2 is null then EAcompl.A_Nacional1
	When EAcompl.A_Nacional3 is null and EAcompl.A_Nacional2 is not null then EAcompl.A_Nacional1 + '/'+ EAcompl.A_Nacional2
	When EAcompl.A_Nacional3 is not null and EAcompl.A_Nacional2 is not null then EAcompl.A_Nacional1 + '/'+ EAcompl.A_Nacional2 + '/' + EAcompl.A_Nacional3
	end,
	EALUNOS.NATURALIDADE, 
	CASE WHEN EALUNOS.SEXO = 'F' THEN 'Feminino'
	WHEN EALUNOS.SEXO = 'M' THEN 'Masculino'
	END, EALUSAUDE.ALERGIAS, EALUSAUDE.REMEDIOS, EALUSAUDE.MEDICOS
FROM
	ZFAMILIA
	INNER JOIN EALUNOS ON (EALUNOS.MATRICULA = ZFAMILIA.MATRICULA)
	INNER JOIN UMATRICPL ON (UMATRICPL.MATALUNO = ZFAMILIA.MATRICULA
				AND UMATRICPL.PERLETIVO = ZFAMILIA.PERLETIVO)
	INNER JOIN EALUSAUDE ON (EALUNOS.MATRICULA = EALUSAUDE.MATALUNO)
	INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
WHERE
	ZFAMILIA.PERLETIVO =:ESPELHO#1
	AND ZFAMILIA.NOME =:ESPELHO#4
	AND ZFAMILIA.PESSOA1 =:ESPELHO#5
	AND ZFAMILIA.PESSOA2 =:ESPELHO#6
	AND UMATRICPL.PERIODO <> 12
