Select
	RTRIM(ZFAMILIA.NOME),
	A_NOMEREDUZIDO,
	RTRIM(A_NACIONAL1) + CASE WHEN RTRIM(A_NACIONAL2) IS NULL THEN '' ELSE '/' + ISNULL(RTRIM(A_NACIONAL2), '') END AS NACIONAL,
	Case 
		when ZFAMILIA.CLASS_PESSOA1 = 'Mãe' then 'Mother'
		when ZFAMILIA.CLASS_PESSOA1 = 'Pai' then 'Father'
		when ZFAMILIA.CLASS_PESSOA1 = 'Responsável Acadêmico' then 'Academic Responsable'
		when ZFAMILIA.CLASS_PESSOA1 = 'Responsável Financeiro' then 'Finance Responsable'
	End as Pessoa1,
	INFOFAMILIA.Nome_Pessoa1,
	Case 
		when ZFAMILIA.CLASS_PESSOA1 = 'Mãe' then RTRIM(EACOMPL.A_NACIONALMAE)
		when ZFAMILIA.CLASS_PESSOA1 = 'Pai' then RTRIM(EACOMPL.A_NACIONALPAI)
	end as NacionalidadePessoas1,
	
	(SELECT EMPRESA FROM PPESSOA (Nolock) WHERE PPESSOA.CODIGO = ZFAMILIA.PESSOA1),

	Case 
		when ZFAMILIA.CLASS_PESSOA2 = 'Mãe' then 'Mother'
		when ZFAMILIA.CLASS_PESSOA2 = 'Pai' then 'Father'
		when ZFAMILIA.CLASS_PESSOA2 = 'Responsável Acadêmico' then 'Academic Responsable'
		when ZFAMILIA.CLASS_PESSOA2 = 'Responsável Financeiro' then 'Finance Responsable'
	End as Pessoa2,
	INFOFAMILIA.Nome_Pessoa2,

	Case 
		when ZFAMILIA.CLASS_PESSOA2 = 'Mãe' then RTRIM(EACOMPL.A_NACIONALMAE)
		when ZFAMILIA.CLASS_PESSOA2 = 'Pai' then RTRIM(EACOMPL.A_NACIONALPAI)
	end as NacionalidadePessoas2,
	
	
	(SELECT EMPRESA FROM PPESSOA (Nolock) WHERE PPESSOA.CODIGO = ZFAMILIA.PESSOA2)
from 
	EACOMPL
INNER JOIN UMATRICPL (NOLOCK) ON (UMATRICPL.MATALUNO = EACOMPL.MATRICULA)
INNER JOIN ZFAMILIA (NOLOCK) ON (ZFAMILIA.PERLETIVO = UMATRICPL.PERLETIVO AND ZFAMILIA.MATRICULA = EACOMPL.MATRICULA)
INNER JOIN VW_Info_Familia INFOFAMILIA (NOLOCK) ON (INFOFAMILIA.Pessoa1 = ZFAMILIA.PESSOA1 AND INFOFAMILIA.Pessoa2 = ZFAMILIA.PESSOA2 AND INFOFAMILIA.Matricula = ZFAMILIA.MATRICULA)
WHERE
	UMATRICPL.PERLETIVO = '13/14'
--AND UMATRICPL.STATUS IN ('01','07')
AND (A_NACIONAL1 = 'AMERICAN' OR A_NACIONAL2 = 'AMERICAN' or A_NACIONAL3 = 'AMERICAN')
ORDER BY ZFAMILIA.NOME, A_NOMEREDUZIDO