
SELECT SUBSTRING ( NOME , 0 , (LEN(NOME)- PATINDEX('% %', REVERSE(NOME))))  FROM EALUNOS WHERE MATRICULA = '00101'



SELECT CODMAT, SUBSTRING(MATERIA, 0, (LEN(MATERIA)- (PATINDEX('%#%', REVERSE(MATERIA))-1))), MATERIA  FROM UMATERIAS
WHERE CODMAT LIKE '%30%'