
/*   ATUALIZA A QUANTIDADE DE ALUNOS MATRICULADOS EM UMA DISCIPLINA */

UPDATE UMATTURMA 
SET NUMALUNOS = (SELECT COUNT(CODTUR) FROM UMATALUN WHERE UMATALUN.CODTUR =UT1.Codtur AND UMATALUN.PERLETIVO = '06/07'AND UMATALUN.CODMAT = UT1.CODMAT)
FROM UMATTURMA UT1
