/* Testa se a 1ª pessoa da família é o Pai, Mãe ou Responsável Financeiro */
--IF (SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00158') IN ('PAI', 'MÃE', 'RESPONSÁVEL ACADÊMICO')

	-------- INICIO PARA TRAZER PAI COMO 1ª PESSOA --------

	/* Verificar se a 1ª pessoa da família é o Pai */
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('PAI') 
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('MÃE'))
		/* Traz o nome da 2ª pessoa da família, caso essa seja a Mãe */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Pai', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.PAI = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Mãe', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.MAE = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END

	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('PAI') 
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL ACADÊMICO'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Acadêmico */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Pai', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.PAI = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Acadêmico', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.RESPACAD = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('PAI') 
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL FINANCEIRO'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Financeiro */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Pai', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.PAI = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Financeiro', FCFO.NOME, 2 AS ORDEM
			FROM
				EALUNOS
				INNER JOIN FCFO ON (EALUNOS.RESPONS = FCFO.CODCFO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END

	-------- FIM PARA TRAZER PAI COMO 1ª PESSOA --------

	-------- INICIO PARA TRAZER MAE COMO 1ª PESSOA --------

	/* Traz o nome da 1ª pessoa da família, caso essa seja a Mãe */
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('MÃE')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('PAI'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Pai */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Mãe', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.MAE = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Pai', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.PAI = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('MÃE')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL ACADÊMICO'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Acadêmico */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Mãe', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.MAE = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Acadêmico', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.RESPACAD = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('MÃE')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL FINANCEIRO'))
		
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Financeiro */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Mãe', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.MAE = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Financeiro', FCFO.NOME, 2 AS ORDEM
			FROM
				EALUNOS
				INNER JOIN FCFO ON (EALUNOS.RESPONS = FCFO.CODCFO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END

	-------- FIM PARA TRAZER MAE COMO 1ª PESSOA -------


	-------- INICIO PARA TRAZER RESPONSAVEL ACADEMICO COMO 1ª PESSOA --------

	/* Traz o nome da 1ª pessoa da família, caso essa seja a Mãe */
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL ACADÊMICO')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('PAI'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Pai */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Acadêmico', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.RESPACAD = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Pai', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.PAI = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL ACADÊMICO')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('MÃE'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Acadêmico */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Acadêmico', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.RESPACAD = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Mãe', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.MAE = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL ACADÊMICO')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL FINANCEIRO'))
		
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Financeiro */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Acadêmico', PPESSOA.NOME, 1 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.RESPACAD = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Financeiro', FCFO.NOME, 2 AS ORDEM
			FROM
				EALUNOS
				INNER JOIN FCFO ON (EALUNOS.RESPONS = FCFO.CODCFO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END

	-------- FIM PARA TRAZER RESPONSAVEL ACADEMICO COMO 1ª PESSOA -------

	-------- INICIO PARA TRAZER RESPONSAVEL FINANCEIRO COMO 1ª PESSOA --------

	/* Traz o nome da 1ª pessoa da família, caso essa seja a Mãe */
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL FINANCEIRO')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('PAI'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Pai */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Financeiro', FCFO.NOME, 1 AS ORDEM
			FROM
				EALUNOS
				INNER JOIN FCFO ON (EALUNOS.RESPONS = FCFO.CODCFO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Pai', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.PAI = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL FINANCEIRO')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('MÃE'))
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Acadêmico */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Financeiro', FCFO.NOME, 1 AS ORDEM
			FROM
				EALUNOS
				INNER JOIN FCFO ON (EALUNOS.RESPONS = FCFO.CODCFO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION
			
			SELECT
				EACOMPL.A_FAMILIA, 'Mãe', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.MAE = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END
		
	IF ((SELECT A_PESSOA1 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL FINANCEIRO')
		AND (SELECT A_PESSOA2 FROM EACOMPL WHERE MATRICULA = '00150') = ('RESPONSÁVEL ACADÊMICO'))
		
		/* Traz o nome da 2ª pessoa da família, caso esse seja o Responsável Financeiro */
		BEGIN
			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Financeiro', FCFO.NOME, 1 AS ORDEM
			FROM
				EALUNOS
				INNER JOIN FCFO ON (EALUNOS.RESPONS = FCFO.CODCFO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			
			UNION

			SELECT
				EACOMPL.A_FAMILIA, 'Responsável Acadêmico', PPESSOA.NOME, 2 AS ORDEM
			FROM 
				EALUNOS
				INNER JOIN PPESSOA ON (EALUNOS.RESPACAD = PPESSOA.CODIGO)
				INNER JOIN EACOMPL ON (EALUNOS.MATRICULA = EACOMPL.MATRICULA)
			WHERE
				EALUNOS.MATRICULA = '00150'
			ORDER BY
				ORDEM
		END

	-------- FIM PARA TRAZER RESPONSAVEL FINANCEIRO COMO 1ª PESSOA -------






