SELECT 
	EALUNOS.NOME,
	EALUNOS.SEXO,
	CASE 
	   WHEN (DATEPART(DAY, EALUNOS.DTNASC)) > (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) > DATEPART(MONTH, GETDATE()) 
 	     OR (DATEPART(DAY, EALUNOS.DTNASC)) < (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) > DATEPART(MONTH, GETDATE())
	     OR (DATEPART(DAY, EALUNOS.DTNASC)) > (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) = DATEPART(MONTH, GETDATE()) 	
             OR (DATEPART(DAY, EALUNOS.DTNASC)) = (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) > DATEPART(MONTH, GETDATE())  
             	THEN DATEPART(YEAR, GETDATE()) - DATEPART(YEAR, EALUNOS.DTNASC) - 1
	   WHEN (DATEPART(DAY, EALUNOS.DTNASC)) > (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) < DATEPART(MONTH, GETDATE()) 
	     OR	(DATEPART(DAY, EALUNOS.DTNASC)) < (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) < DATEPART(MONTH, GETDATE()) 
	     OR	(DATEPART(DAY, EALUNOS.DTNASC)) < (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) = DATEPART(MONTH, GETDATE())  	   
	     OR	(DATEPART(DAY, EALUNOS.DTNASC)) = (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) = DATEPART(MONTH, GETDATE())
	     OR (DATEPART(DAY, EALUNOS.DTNASC)) = (DATEPART(DAY, GETDATE())) AND DATEPART(MONTH, EALUNOS.DTNASC) < DATEPART(MONTH, GETDATE())
		THEN DATEPART(YEAR, GETDATE()) - DATEPART(YEAR, EALUNOS.DTNASC)
        Else ''
	END AS IDADE,
        EALUNOS.DTNASC AS Nascimento,
	EALUNOS.SOBRENOME,
	EALUNOS.USUARIO, UMATRICPL.PERIODO,
	UMATRICPL.PERLETIVO AS 'Ano',
	UCURSOS.NOME AS CURSO,
	UPERIODOS.HABILITACAO,1 AS 'Quantidade',
	USITMAT.DESCRICAO
        
FROM
	EALUNOS LEFT OUTER JOIN
	UMATRICPL ON (
	EALUNOS.MATRICULA=UMATRICPL.MATALUNO
AND	EALUNOS.CODCOLIGADA=UMATRICPL.CODCOLIGADA
AND	EALUNOS.CODFILIAL=UMATRICPL.CODFILIAL) 

	LEFT OUTER JOIN
	UALUCURSO ON (
	UMATRICPL.MATALUNO = UALUCURSO.MATALUNO
AND	UMATRICPL.CODCOLIGADA=UALUCURSO.CODCOLIGADA
AND	UMATRICPL.CODCUR=UALUCURSO.CODCUR
AND	UMATRICPL.CODPER=UALUCURSO.CODPER)
	LEFT OUTER JOIN 
	UCURSOS ON (
	UCURSOS.CODCUR=UALUCURSO.CODCUR)
	LEFT OUTER JOIN
	UPERIODOS ON (
	UPERIODOS.CODCUR=UALUCURSO.CODCUR
AND	UPERIODOS.CODPER=UALUCURSO.CODPER)
	INNER JOIN USITMAT ON UMATRICPL.STATUS = USITMAT.CODSITMAT
order by idade
