SELECT
	MATALUNO, CODMAT, A1, F1, AD1, A2, F2, AD2, A3, F3, AD3, A4, F4, AD4
FROM
	UMATALUN
WHERE
	CODTUR = '7A'
-- 	AND CODMAT = '207HIST'
 	AND MATALUNO = '00100' 
ORDER BY
	CODMAT

/*
UPDATE UMATALUN SET A1 = NULL, A2 = NULL, A3 = NULL, A4 = NULL 
WHERE CODMAT IN (SELECT CODMAT FROM UMATERIAS WHERE SEGUNDONOME = 'BR')
*/
