select * FROM EPROFES
ORDER BY NOME

SELECT * FROM UMATERIAS

SELECT * FROM UPROFMATTURMA, EPROFES, UMATERIAS WHERE UPROFMATTURMA.CODPROF=EPROFES.CODPROF AND UMATERIAS.CODMAT = UPROFMATTURMA.CODMAT 

SELECT UMATERIAS.CODMAT, UMATERIAS.MATERIA,UMATTURMA.NOMETURMA, NOME  
FROM UMATERIAS, UMATTURMA, UPROFMATTURMA, EPROFES
WHERE UMATERIAS.CODMAT = UMATTURMA.CODMAT
AND UMATERIAS.CODMAT = UPROFMATTURMA.CODMAT 
AND UPROFMATTURMA.CODPROF =EPROFES.CODPROF
ORDER BY NOMETURMA


SELECT  distinct
	EPROFES.CODPROF, NOME, MATERIA, UMATTURMA.CODTUR
FROM UPROFMATTURMA, EPROFES, UMATERIAS, UMATTURMA
WHERE UPROFMATTURMA.CODPROF=EPROFES.CODPROF 
AND UMATERIAS.CODMAT = UMATTURMA.CODMAT
AND UMATERIAS.CODMAT = UPROFMATTURMA.CODMAT 
AND UPROFMATTURMA.CODPROF = '1312'
AND UPROFMATTURMA.CodPerlet = '06/07'
ORDER BY NOME, UMATTURMA.CODTUR

