SELECT 
        EPROFES.CHAPA,
	EProfes.Nome,
	Ugrade.CodMatG,
--      LEFT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))),
-- 	LEN(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))))-2)as Hora,
--      RIGHT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))),2) as Minutos,
	case
		when RIGHT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))),2) = '50' then
			LEFT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))), LEN(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))))-2) + ':30'
		else
			LEFT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))), LEN(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))))-2) + ':' + RIGHT(LTRIM(STR((SUM(UPROFMATTURMA.NAULASSEMPROF*4.5)*100))),2)
	end as hora, 			
	GCCUSTO.CODCCUSTO
FROM 
       EPROFES, 
       UPROFMATTURMA,
       UGRADE,
       GCCUSTO
WHERE
       UPROFMATTURMA.TIPOPROF = 'T'
AND    UPROFMATTURMA.CODPERLET='05/06'
AND    EPROFES.CODPROF = UPROFMATTURMA.CODPROF
AND    UGRADE.CODMAT = UPROFMATTURMA.CODMAT
AND    UGRADE.CODMATG = GCCUSTO.CODREDUZIDO
GROUP BY 
       EPROFES.CHAPA,
	EProfes.Nome,
	Ugrade.CodMatG,
       GCCUSTO.CODCCUSTO
ORDER BY
      	EProfes.Nome,	
	Ugrade.CodMatG


