SELECT
 FLAN.IDLAN,
 FCFO.NOMEFANTASIA,
 FCFO.RUAPGTO, FCFO.NUMEROPGTO, FCFO.COMPLEMENTOPGTO, FCFO.BAIRROPGTO,
 FCFO.CIDADEPGTO, FCFO.CODETDPGTO, FCFO.PAISPAGTO,
 EALUNOS.NOME, Umatricpl.periodo, Uperiodos.habilitacao
FROM
 FLAN
 INNER JOIN FCFO ON (FLAN.CODCFO = FCFO.CODCFO)
 LEFT OUTER JOIN EALUNOS ON (EALUNOS.RESPONS = FCFO.CODCFO)
 left outer join UMatricPl(NoLOCK) on (UmatricPl.MatAluno = Ealunos.Matricula)
 inner Join Uperiodos on (Uperiodos.codcur = Umatricpl.codcur and Uperiodos.codper = Umatricpl.codper)
WHERE
 CODTDO = '000016'
 AND DATAVENCIMENTO >= '02/01/2006'
 AND DATAVENCIMENTO <= '02/28/2006'
GROUP BY
 FLAN.IDLAN, FCFO.NOMEFANTASIA, FCFO.RUAPGTO, FCFO.NUMEROPGTO, FCFO.COMPLEMENTOPGTO, FCFO.BAIRROPGTO,
 FCFO.CIDADEPGTO, FCFO.CODETDPGTO, FCFO.PAISPAGTO, EALUNOS.NOME, Umatricpl.periodo,Uperiodos.habilitacao
ORDER BY
 FCFO.NOMEFANTASIA