SELECT MATRICULA, EALUNOS.NOME, PAI, PPESSOA.NOME FROM EALUNOS, PPESSOA WHERE PAI=CODIGO  and PPESSOA.NOME IN
(
SELECT NOME
FROM PPESSOA 
GROUP BY NOME
HAVING COUNT(PPESSOA.NOME) >1
)
ORDER BY PPESSOA.NOME

SELECT MATRICULA, EALUNOS.NOME, PAI, PPESSOA.NOME FROM EALUNOS, PPESSOA WHERE PAI=CODIGO ORDER BY PPESSOA.NOME

SELECT * FROM PPESSOA WHERE 
PPESSOA.NOME IN
(
SELECT NOME
FROM PPESSOA 
GROUP BY NOME
HAVING COUNT(PPESSOA.NOME) >1
)
ORDER BY PPESSOA.NOME
NOT IN 
(SELECT DISTINCT CODIGO FROM PPESSOA WHERE CODIGO IN (SELECT DISTINCT PAI FROM EALUNOS))
ORDER BY PPESSOA.NOME

