UPDATE UMATALUN SET 
-- 	A2 = NULL, AD2 = NULL, F2 = NULL
	A3 = NULL, AD3 = NULL, F3 = NULL
	,A4 = NULL, AD4 = NULL, F4 = NULL 
	,A5 = NULL, AD5 = NULL, F5 = NULL
-- 	,A6 = NULL, AD6 = NULL, F6 = NULL
	,A7 = NULL, AD7 = NULL, F7 = NULL
	,A8 = NULL, AD8 = NULL, F8 = NULL
	,A9 = NULL, AD9 = NULL, F9 = NULL
	,A10 = NULL, AD10 = NULL, F10 = NULL
	,A0 = NULL, AD0 = NULL, F0 = NULL
	, STATUS = '01', PERCFREQ = NULL
-- 
-- 
-- 
-- UPDATE UMATALUN SET 
-- 	A2 = NULL, AD2 = NULL, F2 = NULL 
WHERE
	CODTUR = '6B'
	AND CODMAT = '206BHG'
-- 	AND MATALUNO <> '00177'
-- 	AND MATALUNO = '00146'