select distinct
     Ealubolsa.MatAluno,  
     (Select top 1 Nome from FCFO where CodCFo = respons) as Responsavel_$,
     Rtrim(A_NomeReduzido)as Nome,
     (Select top 1 CodTur from UMatAlun  where UMatAlun.MatAluno = Eacompl.Matricula  and Ealubolsa.perletivo = UMatAlun.Perletivo Group by UMatAlun.CodTur Order by count(UMatAlun.CodTur) desc) as Grade_Level, 
      DescBolsa, Ealubolsa.CodBol
/*, SERVICO_DESC,
	Ealubolsa.PercDesc,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.Perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 1 and ((A_DataEntradaISC <= AugustEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= AugustEnd and A_DataSaidaISC > AugustBegin) OR ( A_ReturnedToISC <= AugustEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= AugustEnd and A_LeftISC_2 > AugustBegin))) end AS AGOSTO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 2 and ((A_DataEntradaISC <= SeptemberEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= SeptemberEnd and A_DataSaidaISC > SeptemberBegin) OR ( A_ReturnedToISC <= SeptemberEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= SeptemberEnd and A_LeftISC_2 > SeptemberBegin))) end AS SETEMBRO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 3 and ((A_DataEntradaISC <= OctoberEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= OctoberEnd and A_DataSaidaISC > OctoberBegin) OR ( A_ReturnedToISC <= OctoberEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= OctoberEnd and A_LeftISC_2 > OctoberBegin))) end AS OUTUBRO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 4 and ((A_DataEntradaISC <= NovemberEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= NovemberEnd and A_DataSaidaISC > NovemberBegin) OR ( A_ReturnedToISC <= NovemberEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= NovemberEnd and A_LeftISC_2 > NovemberBegin))) end AS NOVEMBRO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 5 and ((A_DataEntradaISC <= DecemberEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= DecemberEnd and A_DataSaidaISC > DecemberBegin) OR ( A_ReturnedToISC <= DecemberEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= DecemberEnd and A_LeftISC_2 > DecemberBegin))) end AS DEZEMBRO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 6 and ((A_DataEntradaISC <= JanuaryEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= JanuaryEnd and A_DataSaidaISC > JanuaryBegin) OR ( A_ReturnedToISC <= JanuaryEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= JanuaryEnd and A_LeftISC_2 > JanuaryBegin))) end AS JANEIRO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 7 and ((A_DataEntradaISC <= FebruaryEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= FebruaryEnd and A_DataSaidaISC > FebruaryBegin) OR ( A_ReturnedToISC <= FebruaryEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= FebruaryEnd and A_LeftISC_2 > FebruaryBegin))) end AS FEVEREIRO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 8 and ((A_DataEntradaISC <= MarchEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= MarchEnd and A_DataSaidaISC > MarchBegin) OR ( A_ReturnedToISC <= MarchEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= MarchEnd and A_LeftISC_2 > MarchBegin))) end AS MARCO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 9 and ((A_DataEntradaISC <= AprilEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= AprilEnd and A_DataSaidaISC > AprilBegin) OR ( A_ReturnedToISC <= AprilEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= AprilEnd and A_LeftISC_2 > AprilBegin))) end AS ABRIL,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 10 and ((A_DataEntradaISC <= MayEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= MayEnd and A_DataSaidaISC > MayBegin) OR ( A_ReturnedToISC <= MayEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= MayEnd and A_LeftISC_2 > MayBegin))) end AS MAIO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 11 and ((A_DataEntradaISC <= JuneEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= JuneEnd and A_DataSaidaISC > JuneBegin) OR ( A_ReturnedToISC <= JuneEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= JuneEnd and A_LeftISC_2 > JuneBegin))) end AS JUNHO,
Case When TipoDesc = 'V' then Ealubolsa.PercDesc else (Ealubolsa.PercDesc/100)*(select sum(valor) from EmodConpC Inner Join EmodContr (NoLock) on ( EmodContr.CodMod = EmodConpC.Modelo and EmodContr.CodPerlet = EmodConpC.CodPerlet) inner Join EaluServ (NoLock) on (EaluServ.PerLetivo = EmodConpC.CodPerlet and EaluServ.MatAluno = Ealubolsa.MatAluno and EaluServ.Plano = EmodConpC.Modelo) Inner Join Z_SchoolCalendar (NoLock) on (Ealubolsa.perletivo = Z_SchoolCalendar.CodPerlet) where EmodConpC.CodPerlet = Ealubolsa.perletivo and EmodConpC.CodServ = Ealubolsa.CodServico and EmodConpC.Parcela= 12 and ((A_DataEntradaISC <= JulyEnd and A_DataSaidaISC is null) OR (A_DataEntradaISC <= JulyEnd and A_DataSaidaISC > JulyBegin) OR ( A_ReturnedToISC <= JulyEnd and A_LeftISC_2 is null) OR (A_ReturnedToISC <= JulyEnd and A_LeftISC_2 > JulyBegin))) end AS JULHO */
from Ealubolsa 
inner Join ETipobols (NoLock) on (ETipobols.CodBolsa = Ealubolsa.CodBol)
inner join Eservicos (NoLock) on (EServicos.Servico_Cod = Ealubolsa.CodServico)
inner join Ealunos (NoLock) on (Ealunos.Matricula =  Ealubolsa.MatAluno)
inner Join EACompl (NoLock) on (Eacompl.Matricula = Ealubolsa.MatAluno)
where Ealubolsa.perletivo ='09/10'
--and codbolsa in (25, 50, 75, 100)
Order By grade_level




