/*
select distinct(MATALUNO) from UMATRICPL
where PERLETIVO = '16/17'
	and UMATRICPL.status in ('01','07','18','06')
	*/

	/*
	Conferencia de enrollment de alunos
	*/


SELECT distinct
	umatricpl.MATALUNO, A_DATAENTRADAISC, A_DATASAIDAISC, A_RETURNEDTOISC, A_LEFTISC_2, UMATRICPL.STATUS, EALUNOS.TIPOALUNO, UMATRICPLLIVRE.M_TURMA,
	E.CODBOL, E.DTINICIO, E.DTFIM
from UMATRICPL 
	inner join UMATRICPLLIVRE on UMATRICPL.MATALUNO = UMATRICPLLIVRE.MATALUNO and UMATRICPL.PERLETIVO = UMATRICPLLIVRE.PERLETIVO
	inner join EACOMPL on UMATRICPL.MATALUNO = EACOMPL.MATRICULA
	inner join EALUNOS on EALUNOS.MATRICULA = EACOMPL.MATRICULA
	inner join Z_SchoolCalendar z on z.CodPerlet = UMATRICPL.PERLETIVO
	inner join EALUBOLSA E ON E.MATALUNO = UMATRICPL.MATALUNO AND E.PERLETIVO = UMATRICPL.PERLETIVO
where umatricpl.PERLETIVO = '16/17' --and UMATRICPL.status in ('01','07','18','06')
and  EALUNOS.TIPOALUNO in (5) 
AND E.CODBOL = 50
AND E.DTFIM >= z.JuneEnd -- AND E.DTINICIO <= z.AprilBegin
--and UMATRICPL.CODCUR = 3 and umatricpl.CODPER = 1-- and umatricpl.PERIODO in (9)
AND
(
				(EACOMPL.A_DATAENTRADAISC < z.JuneEnd AND (EACOMPL.A_DATASAIDAISC is null) or (EACOMPL.A_DATASAIDAISC >= z.JuneEnd)) or
				(EACOMPL.A_DATASAIDAISC IS NOT NULL AND EACOMPL.A_RETURNEDTOISC is not null and A_LEFTISC_2 IS NULL)
				OR EACOMPL.A_LEFTISC_2 >= z.JuneEnd
			)
	/*	
and  ((A_DataEntradaISC <= '08-31-2016' and A_DataSaidaISC is null) 
OR 	(A_DataEntradaISC <= '08-31-2016' and A_DataSaidaISC > '08-31-2016')
OR 	(A_ReturnedToISC <= '08-31-2016' and A_LeftISC_2 is null) 
OR 	(A_ReturnedToISC <= '08-31-2016' and A_LeftISC_2 > '08-31-2016'))
*/

--COMPUTE COUNT(UMATRICPL.MATALUNO)