SELECT 
	
	(SELECT CHAPA FROM PFUNC WHERE PFUNC.NOME LIKE F.NOMEFANTASIA AND PFUNC.CODSITUACAO NOT IN ('U','D')) AS StaffID, 
	(SELECT NOME FROM PFUNC WHERE PFUNC.NOME LIKE F.NOMEFANTASIA AND PFUNC.CODSITUACAO NOT IN ('U','D')) AS StaffName,
	CAST((SELECT DATAADMISSAO FROM PFUNC WHERE PFUNC.NOME LIKE F.NOMEFANTASIA AND PFUNC.CODSITUACAO NOT IN ('U','D'))AS DATE) AS StaffStartDate,
	E.MATRICULA as StudentID, 
	E.NOME as StudentName, 
	CAST(EA.A_DATAENTRADAISC AS date) as StudentStartDate,
	--U.CODCUR, U.CODPER, U.PERIODO,
	CASE
		WHEN U.CODCUR = 1 AND U.PERIODO = 1 THEN 'TODDLER'
		WHEN U.CODCUR = 1 AND U.PERIODO = 2 THEN 'NURSERY'
		WHEN U.CODCUR = 1 AND U.PERIODO = 3 THEN 'PRE-K'
		WHEN U.CODCUR = 1 AND U.PERIODO = 4 THEN 'KINDER'
		ELSE 
			CAST(U.PERIODO AS varchar) + ' GRADE'
	END as StudentGrade
	--F.NOMEFANTASIA, F.NOME,
FROM EALUNOS E
	INNER JOIN UMATRICPL U ON U.MATALUNO = E.MATRICULA
	INNER JOIN EACOMPL EA ON EA.MATRICULA = E.MATRICULA
	INNER JOIN FCFO F ON F.CODCFO = E.RESPONS
WHERE
	U.PERLETIVO = '16/17' AND
	E.TIPOALUNO = 5
ORDER BY
	(SELECT CHAPA FROM PFUNC WHERE PFUNC.NOME LIKE F.NOMEFANTASIA AND PFUNC.CODSITUACAO NOT IN ('U','D'))