select AQUISICAO,  valorbasecorrigido , DEPRECIACAOACUMULADACORRIGIDA,
* from ISALDOCALCULOPATRIMONIOMOEDA 
inner join IPATRIMONIO (Nolock) on (ISALDOCALCULOPATRIMONIOMOEDA.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO)
where
-- AQUISICAO <>  valorbasecorrigido 
 IDGRUPOPATRIMONIO = (Select IGRUPOPATRIMONIO.IDGRUPOPATRIMONIO from IGRUPOPATRIMONIO where CODGRUPOPATRIMONIO= '007')
and IPATRIMONIO.ATIVO = 1
and valorbasecorrigido <> valorbase
and IPATRIMONIO.idpatrimonio  in (1702)

/*
update ISALDOCALCULOPATRIMONIOMOEDA 
set valorbasecorrigido = 1794.11

from ISALDOCALCULOPATRIMONIOMOEDA
inner join IPATRIMONIO (Nolock) on (ISALDOCALCULOPATRIMONIOMOEDA.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO)
where
-- AQUISICAO <>  valorbasecorrigido 
IDGRUPOPATRIMONIO = (Select IGRUPOPATRIMONIO.IDGRUPOPATRIMONIO from IGRUPOPATRIMONIO where CODGRUPOPATRIMONIO= '007')
and IPATRIMONIO.ATIVO = 1
and IPATRIMONIO.idpatrimonio  in (95)


*/
select 
	ICALCULORAZAO.DEPRECIACAOACUMULADA,
	ICALCULORAZAO.DEPRECIACAOACUMULADACORRIGIDA,
	DEPRECIACAO,
	DEPRECIACAOAJUSTADA,
	AQUISICAO, VALORBASE,
	VALORBASECORRIGIDO, 
	* 
from ICALCULORAZAO 
inner join IPATRIMONIO (Nolock) on (ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO)
where
	IDCALCULORAZAO = 2
and ICALCULORAZAO.DEPRECIACAO = 0 -- DEPRECIACAOAJUSTADA --ICALCULORAZAO.DEPRECIACAOAJUSTADA
--and AQUISICAO <>VALORBASECORRIGIDO 
and IDGRUPOPATRIMONIO = (Select IGRUPOPATRIMONIO.IDGRUPOPATRIMONIO from IGRUPOPATRIMONIO where CODGRUPOPATRIMONIO= '007')
and	ICALCULORAZAO.DEPRECIACAOACUMULADA <> ICALCULORAZAO.DEPRECIACAOACUMULADACORRIGIDA


AND IPATRIMONIO.IDPATRIMONIO IN (1053,1054,1055,1056,1070,1071,1074,1078,
1082,1083,1084,1085,
1086,1087,1088,1089,
1090,1091,1092,1093,
1094,1096,1097,1098,
1099,1100,1101,1102)

select * from IPATRIMONIO where IDPATRIMONIO = 507
/*
update ICALCULORAZAO 
set 	ICALCULORAZAO.DEPRECIACAOACUMULADACORRIGIDA = 2160.00
from ICALCULORAZAO
inner join IPATRIMONIO (Nolock) on (ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO)
where
	IDCALCULORAZAO = 1
and ICALCULORAZAO.DEPRECIACAOACUMULADACORRIGIDA <> DEPRECIACAOACUMULADA --ICALCULORAZAO.DEPRECIACAOAJUSTADA
--and VALORBASE <>VALORBASECORRIGIDO 
and IDGRUPOPATRIMONIO = (Select IGRUPOPATRIMONIO.IDGRUPOPATRIMONIO from IGRUPOPATRIMONIO where CODGRUPOPATRIMONIO= '007')
AND IPATRIMONIO.IDPATRIMONIO IN (77)

*/
select * from IPATRIMONIO where IDPATRIMONIO >= 77

select * from IPATRIMONIO where CODPATRIMONIO = '08.0715'


/*

Para o acerto da conta de Máquinas e equipamentos (grupo 8) o Patrimonio 08.0140 é o que contem o valor do ajuste.
	CONTA 87 - AQUISICAO: ICALCULORAZAO.VALORBASECORRIGIDO
	CONTA 97 - DEPRECIACAO: ICALCULORAZAO.DEPRECIACAOAJUSTADA

Moveis e Utensilios
09.0193
09.0890

*/