/* Listagem para atualização do Código de Barras */

SELECT CODCOLIGADA, CODFILIAL, TIPOPATRIMONIO, IDPATRIMONIO, CODPATRIMONIO, PATRIMONIO, CODIGOBARRA, DESCRICAO
FROM IPATRIMONIO
--WHERE IDPATRIMONIO = 1804
order by PATRIMONIO

/*
UPDATE IPATRIMONIO SET PATRIMONIO = '00001', CODIGOBARRA = '00001' 
WHERE IDPATRIMONIO = 1804 AND CODPATRIMONIO = '09.0161' AND PATRIMONIO = '80001' AND CODIGOBARRA = '80001' AND CODCOLIGADA = 1
*/