select * from ISALDOCALCULOPATRIMONIOMOEDA where  IDPATRIMONIO = 1836

where IDPATRIMONIO in (select IDPATRIMONIO from IPATRIMONIO where IDGRUPOPATRIMONIO = 4 )


compute sum(VALORBASE)



select * from IPATRIMONIO where IDPATRIMONIO  in (select IDPATRIMONIO from ISALDOCALCULOPATRIMONIOMOEDA where DATABASEPATRIMONIO <= '01/01/2013')
and IDPATRIMONIO = 1836



update ISALDOCALCULOPATRIMONIOMOEDA set VALORBASE = VALORBASE + 550.00, VALORBASECORRIGIDO = VALORBASECORRIGIDO + 550.00  where IDPATRIMONIO = 1836


select * from ISALDOCALCULOPATRIMONIOMOEDA where IDPATRIMONIO = 1836