select 
		(SELECT IPATRIMONIO.CODCENTROCUSTO FROM IPATRIMONIO WHERE IPATRIMONIO.IDPATRIMONIO = ICALCULORAZAO.IDPATRIMONIO) AS CCUSTO, 
		DEPRECIACAO, IDPATRIMONIO
from 
	ICALCULORAZAO  
where 
	DATA = '12/31/2015' 
and ICALCULORAZAO.IDPATRIMONIO 
	in (select IDPATRIMONIO from IPATRIMONIO where IDGRUPOPATRIMONIO = (select IDGRUPOPATRIMONIO from IGRUPOPATRIMONIO where CODGRUPOPATRIMONIO = '009'))
and DEPRECIACAO > 0
AND (SELECT IPATRIMONIO.CODCENTROCUSTO FROM IPATRIMONIO WHERE IPATRIMONIO.IDPATRIMONIO = ICALCULORAZAO.IDPATRIMONIO) = '1.01.01.06.60.6000' 



order by IDPATRIMONIO, CCUSTO, DEPRECIACAO
compute sum(depreciacao)