/*
	- Extrato de Saldo Depreciação a depreciar
*/

SELECT
	IPATRIMONIO.CODPATRIMONIO, IPATRIMONIOMOEDA.AQUISICAO,
	IPATRIMONIO.DESCRICAO, IPATRIMONIO.DATAAQUISICAO,
	(SELECT TOP 1 SALDORESIDUAL FROM ICALCULORAZAO 
	WHERE 
		ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
	ORDER BY ICALCULORAZAO.DATA DESC
	) AS SALDO,
	(SELECT TOP 1 DEPRECIACAOACUMULADA FROM ICALCULORAZAO 
	WHERE 
		ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
	ORDER BY ICALCULORAZAO.DATA DESC
	) AS DEPACUMULADA,
	(SELECT TOP 1 TAXADEPRECIACAOPERIODO FROM ICALCULORAZAO 
	WHERE 
		ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
	ORDER BY ICALCULORAZAO.DATA DESC
	) * 12 AS TXDEPANO
FROM 
	IPATRIMONIO
	JOIN IPATRIMONIOMOEDA ON IPATRIMONIOMOEDA.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
	--INNER JOIN ICALCULORAZAO ON ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
WHERE 
	IPATRIMONIO.ATIVO = 1 AND
	(SELECT TOP 1 SALDORESIDUAL FROM ICALCULORAZAO 
	WHERE ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
	ORDER BY ICALCULORAZAO.DATA DESC
	) IS NOT NULL AND
	(SELECT TOP 1 SALDORESIDUAL FROM ICALCULORAZAO 
	WHERE ICALCULORAZAO.IDPATRIMONIO = IPATRIMONIO.IDPATRIMONIO
	ORDER BY ICALCULORAZAO.DATA DESC) > 0
ORDER BY
	IPATRIMONIO.DATAAQUISICAO

	/*
SELECT * FROM IRAZAO


SELECT IBEM.DESCRICAO, IBEM.DTAQUISICAO, VRBASEINDICE, 
* 
FROM IBEM
	INNER JOIN ICALCULORAZAO ON ICALCULORAZAO.CODPATRIMONIO = IBEM.CODBEM
WHERE IBEM.ATIVO = 1 */