/* Listagem de Patrimonios Baixados Totalmente - em um período*/
SELECT 
	IPATRIMONIO.CODPATRIMONIO, IPATRIMONIO.DATAAQUISICAO, IPATRIMONIO.DESCRICAO,
	IOCORRENCIA.DATA, IGRUPOPATRIMONIO.CODGRUPOPATRIMONIO, IGRUPOPATRIMONIO.DESCRICAO,
	IPATRIMONIO.AQUISICAO, IOCORRENCIA.VALOROCORRENCIA
FROM IPATRIMONIO
INNER JOIN IOCORRENCIA ON IOCORRENCIA.CODCOLIGADA = IPATRIMONIO.CODCOLIGADA 
	AND IOCORRENCIA.IDPATRIMONIOORIGEM = IPATRIMONIO.IDPATRIMONIO
INNER JOIN IGRUPOPATRIMONIO ON IGRUPOPATRIMONIO.IDGRUPOPATRIMONIO = IPATRIMONIO.IDGRUPOPATRIMONIO
WHERE IOCORRENCIA.TIPO = 99
AND IOCORRENCIA.DATA >= '08-01-2016' AND IOCORRENCIA.DATA <= '07-31-2017'