SELECT 
--*,
	CODIGO,
	PEVENTO.DESCRICAO,
	NATRUBRICA,
	CODRUBRICA,
	PRUBRICA.DESCRICAO
FROM PEVENTO
	LEFT JOIN PRUBRICA ON PRUBRICA.CODCLIENTE = PEVENTO.CODRUBRICA
	

--SELECT * FROM GLINKSREL WHERE MASTERTABLE= 'homologrub'