/*Conferência de Lanc Educacional para Financeiro*/
SELECT 
	ESERVICOS.SERVICO_DESC, EDESCLAN.PARCELA, EDESCLAN.PLANO, 
	SUM(VALOR1) AS ORIGINAL, SUM(valortot) AS ORI_COM_DESC, SUM(VLRDESC1) AS DESCONTO, SUM(VALORBAIXADO) AS PAGO,
	MONTH(EDESCLAN.DATA) AS MES_COMP,  YEAR(EDESCLAN.DATA) AS ANO_COMP
	FROM EDESCLAN
	INNER JOIN ESERVICOS ON ESERVICOS.SERVICO_COD = EDESCLAN.TIPOLANC
	INNER JOIN FLAN ON FLAN.IDLAN = EDESCLAN.CODLANC AND FLAN.CODCOLIGADA = EDESCLAN.CODCOLIGADA
WHERE 
	EDESCLAN.PERLETIVO = '17/18'
GROUP BY
	ESERVICOS.SERVICO_DESC, EDESCLAN.PLANO, EDESCLAN.PARCELA, MONTH(EDESCLAN.DATA), YEAR(EDESCLAN.DATA)
ORDER BY
	ESERVICOS.SERVICO_DESC, EDESCLAN.PLANO, EDESCLAN.PARCELA, MONTH(EDESCLAN.DATA), YEAR(EDESCLAN.DATA)


/*
SELECT * FROM EDESCLAN 
INNER JOIN FLAN ON FLAN.IDLAN = EDESCLAN.CODLANC AND FLAN.CODCOLIGADA = EDESCLAN.CODCOLIGADA
WHERE EDESCLAN.PERLETIVO = '17/18' and plano is null
*/



/*
SELECT * FROM GLINKSREL
WHERE MASTERTABLE = 'ESERVICOS'
*/