SELECT INTEGRADO FROM GINTEGRACAO WHERE (CODCOLIGADA = 0 OR CODCOLIGADA = 1) AND ((CODSISTEMA1 = 'P' AND CODSISTEMA2 = 'V') OR (CODSISTEMA1 = 'V' AND CODSISTEMA2 = 'P')) ORDER BY CODCOLIGADA DESC
go
SELECT 1 FROM VCONTROLESISTEMA (NOLOCK) WHERE CODCOLIGADA = 1 AND USATABSAL = 1
go
SELECT CODCOLIGADA, CODFAIXA, NOMEFAIXA FROM VFAIXASALARIAL (NOLOCK) WHERE CODCOLIGADA = 1
go
SELECT 1 FROM VCONTROLESISTEMA (NOLOCK) WHERE CODCOLIGADA = 1 AND USATABSAL = 1
go
SELECT CODNIVEL, NOMENIVEL FROM VNIVELFUNCAO (NOLOCK) WHERE CODCOLIGADA = 1
go
SELECT INTEGRADO FROM GINTEGRACAO WHERE (CODCOLIGADA = 0 OR CODCOLIGADA = 1) AND ((CODSISTEMA1 = 'P' AND CODSISTEMA2 = 'V') OR (CODSISTEMA1 = 'V' AND CODSISTEMA2 = 'P')) ORDER BY CODCOLIGADA DESC
go
SELECT CODCOLIGADA, CODIGO, NOME, CBO FROM PFUNCAO WHERE (CODCOLIGADA = 1) AND (INATIVA = 0) ORDER BY NOME
go
SELECT INTEGRADO FROM GINTEGRACAO WHERE (CODCOLIGADA = 0 OR CODCOLIGADA = 1) AND ((CODSISTEMA1 = 'P' AND CODSISTEMA2 = 'V') OR (CODSISTEMA1 = 'V' AND CODSISTEMA2 = 'P')) ORDER BY CODCOLIGADA DESC
go
SELECT 1 FROM VCONTROLESISTEMA (NOLOCK) WHERE CODCOLIGADA = 1 AND USATABSAL = 1
go
SELECT CODCOLIGADA, CODFAIXA, NOMEFAIXA FROM VFAIXASALARIAL (NOLOCK) WHERE CODCOLIGADA = 1
go
SELECT 1 FROM VCONTROLESISTEMA (NOLOCK) WHERE CODCOLIGADA = 1 AND USATABSAL = 1
go
SELECT CODNIVEL, NOMENIVEL FROM VNIVELFUNCAO (NOLOCK) WHERE CODCOLIGADA = 1
go
SELECT INTEGRADO FROM GINTEGRACAO WHERE (CODCOLIGADA = 0 OR CODCOLIGADA = 1) AND ((CODSISTEMA1 = 'P' AND CODSISTEMA2 = 'V') OR (CODSISTEMA1 = 'V' AND CODSISTEMA2 = 'P')) ORDER BY CODCOLIGADA DESC
go
SELECT CODCOLIGADA, CODIGO, DESCRICAO, CODFILIAL , CGC FROM PSECAO (NOLOCK) WHERE (CODCOLIGADA = 1) AND PSECAO.SECAODESATIVADA <> 1 AND (CODIGO LIKE '____') ORDER BY DESCRICAO
go
