/* RELACAO DE COMPANHIAS Vs FUNDO DE DESENVOLVIMENTO */

/*
SELECT 
	TIPOALUNO, UMATRICPL.MATALUNO, EACOMPL.A_COMPANHIA,
	EDESCLAN.PLANO,
	CASE 
		WHEN EDESCLAN.PLANO LIKE '%50%' THEN '50'
	ELSE	
		'100'
	END AS DESCONTO, 
	EDESCLAN.VALOR1
FROM
	EALUNOS
	INNER JOIN UTABTIPO (NOLOCK) ON (UTABTIPO.CODTIPO = EALUNOS.TIPOALUNO)
	INNER JOIN UMATRICPL (NOLOCK) ON (UMATRICPL.MATALUNO = EALUNOS.MATRICULA)
	INNER JOIN EDESCLAN (NOLOCK) ON (EDESCLAN.MATALUNO = EALUNOS.MATRICULA AND EDESCLAN.PERLETIVO = UMATRICPL.PERLETIVO AND EDESCLAN.DESCRICAO LIKE '%FUND%' AND EDESCLAN.TIPOLANC = '7')
	INNER JOIN EACOMPL (NOLOCK) ON (EACOMPL.MATRICULA = EALUNOS.MATRICULA)
WHERE
	EALUNOS.TIPOALUNO IN ('3', '4')
AND UMATRICPL.PERLETIVO = '14/15'
AND UMATRICPL.STATUS IN ('01','07')
order by DESCONTO DESC

--=================================================================== */


/* RELACAO DE LOCAL/TEMPRARIO Vs FUNDO DE DESENVOLVIMENTO */

/*
SELECT DISTINCT UMATRICPL.STATUS,
	TIPOALUNO, UMATRICPL.MATALUNO, EACOMPL.A_COMPANHIA,
	EDESCLAN.PLANO,
	EDESCLAN.VALOR1,
	EDESCLAN.PERCDESC, 
	EDESCLAN.VALORTOT
	
FROM
	EALUNOS
	INNER JOIN UTABTIPO (NOLOCK) ON (UTABTIPO.CODTIPO = EALUNOS.TIPOALUNO)
	INNER JOIN UMATRICPL (NOLOCK) ON (UMATRICPL.MATALUNO = EALUNOS.MATRICULA)
	INNER JOIN EDESCLAN (NOLOCK) ON (EDESCLAN.MATALUNO = EALUNOS.MATRICULA AND EDESCLAN.PERLETIVO = UMATRICPL.PERLETIVO AND EDESCLAN.TIPOLANC = '7')
	INNER JOIN EACOMPL (NOLOCK) ON (EACOMPL.MATRICULA = EALUNOS.MATRICULA)
WHERE
	EALUNOS.TIPOALUNO IN ('1', '2')
AND UMATRICPL.PERLETIVO = '14/15'
--AND UMATRICPL.STATUS IN ('01','07','14')
AND UMATRICPL.MATALUNO = 01415
order by PERCDESC DESC


--=================================================================== */


/* RELACAO DE OUTROS Vs FUNDO DE DESENVOLVIMENTO */

/*
SELECT 
	TIPOALUNO, UMATRICPL.MATALUNO, EACOMPL.A_COMPANHIA	
FROM
	EALUNOS
	INNER JOIN UTABTIPO (NOLOCK) ON (UTABTIPO.CODTIPO = EALUNOS.TIPOALUNO)
	INNER JOIN UMATRICPL (NOLOCK) ON (UMATRICPL.MATALUNO = EALUNOS.MATRICULA)
	INNER JOIN EACOMPL (NOLOCK) ON (EACOMPL.MATRICULA = EALUNOS.MATRICULA)
WHERE
	EALUNOS.TIPOALUNO = 5
AND UMATRICPL.PERLETIVO = '14/15'
AND UMATRICPL.STATUS IN ('01','07')

--=================================================================== */

/* RELACAO DE OUTROS Vs FUNDO DE DESENVOLVIMENTO */

/*
SELECT 
	TIPOALUNO, UMATRICPL.MATALUNO,EACOMPL.A_NOMEREDUZIDO, EACOMPL.A_DATAENTRADAISC, UMATRICPL.STATUS, EACOMPL.A_COMPANHIA	
FROM
	EALUNOS
	INNER JOIN UTABTIPO (NOLOCK) ON (UTABTIPO.CODTIPO = EALUNOS.TIPOALUNO)
	INNER JOIN UMATRICPL (NOLOCK) ON (UMATRICPL.MATALUNO = EALUNOS.MATRICULA)
	INNER JOIN EACOMPL (NOLOCK) ON (EACOMPL.MATRICULA = EALUNOS.MATRICULA)
WHERE
	EALUNOS.TIPOALUNO IN ('1', '2')
AND UMATRICPL.PERLETIVO = '14/15'
AND UMATRICPL.STATUS IN ('01','07')
AND EALUNOS.MATRICULA NOT IN (SELECT MATALUNO FROM EDESCLAN WHERE EDESCLAN.MATALUNO = EALUNOS.MATRICULA AND EDESCLAN.PERLETIVO = UMATRICPL.PERLETIVO AND EDESCLAN.TIPOLANC = '7')
order by EACOMPL.MATRICULA 
--=================================================================== */

--select * from UMATRICPL where MATALUNO in (
SELECT	
	EALUBOLSA.CODBOL,
	ESERVICOS.SERVICO_DESC,
	ETIPOBOLS.DESCBOLSA,
	EALUBOLSA.PERCDESC,
	EALUBOLSA.TIPODESC,
--	COUNT(EALUBOLSA.MATALUNO)AS TOTAL
	EALUBOLSA.MATALUNO
FROM 
	EALUBOLSA 
	INNER JOIN ETIPOBOLS (NOLOCK) ON (ETIPOBOLS.CODBOLSA = EALUBOLSA.CODBOL)
	INNER JOIN ESERVICOS (NOLOCK) ON (ESERVICOS.SERVICO_COD = EALUBOLSA.CODSERVICO)
WHERE 
	EALUBOLSA.PERLETIVO = '14/15' and CODBOL = 311) and PERLETIVO = '14/15'
--GROUP BY EALUBOLSA.CODBOL, ETIPOBOLS.DESCBOLSA, ESERVICOS.SERVICO_DESC, EALUBOLSA.PERCDESC,	EALUBOLSA.TIPODESC

-- SELECT * FROM ESERVICOS WHERE PERLETIVO = '14/15' and mataluno = 00077 AND DESCRICAO LIKE '%FUND%' AND TIPOLANC = '7' AND PLANO LIKE '%50%'


select * from edesclan where VALORTOT = '4562.00' and perletivo = '14/15'








