/* Professores por disciplina */

SELECT 
	DISTINCT 
	UCURSOS.SEGUNDONOME, UPERIODOS.NOME, UMATTURMA.CODCUR, UMATTURMA.CODPER,
	UPROFMATTURMA.CODMAT, UMATERIAS.MATERIA, UMATTURMA.CODTUR, UMATTURMA.NOMETURMA, EPROFES.NOME
FROM 
	UPROFMATTURMA
	INNER JOIN EPROFES ON EPROFES.CODPROF = UPROFMATTURMA.CODPROF
	INNER JOIN UMATERIAS ON UMATERIAS.CODMAT = UPROFMATTURMA.CODMAT
	INNER JOIN PFUNC ON PFUNC.CHAPA = EPROFES.CHAPA
	INNER JOIN UMATTURMA ON UMATTURMA.CODTUR = UPROFMATTURMA.CODTUR AND UMATTURMA.CODPERLET = UPROFMATTURMA.CODPERLET
	INNER JOIN UCURSOS ON UCURSOS.CODCUR = UMATTURMA.CODCUR
	INNER JOIN UPERIODOS ON UPERIODOS.CODPER = UMATTURMA.CODPER AND UPERIODOS.CODCUR = UMATTURMA.CODCUR
WHERE 
	TIPOPROF = 'T'
	AND UPROFMATTURMA.CODPERLET = '17/18'
	--AND PFUNC.CODSITUACAO = 'D'
	AND UMATTURMA.CODCUR = 1
ORDER BY
	UMATTURMA.CODCUR, UMATTURMA.CODPER, UPROFMATTURMA.CODMAT, UMATTURMA.CODTUR

--SELECT CODPROF, NOME FROM EPROFES