Select Distinct
	Case when ZFam.Lingua = 'English' then SUBSTRING(ZFam.Nome, 1, len(ZFam.Nome)) + ' Family' 
	Else 'Família ' + SUBSTRING(ZFam.Nome, 1, len(ZFam.Nome)) End as Familia,
--	ZFam.Pessoa1,
--	ZFam.Pessoa2,
--	(Select Top 1 EACompl.Matricula      from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc) as Matriculas,
--	(Select Top 1 EACompl.A_NomeReduzido from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc) as NomeIng,
	(Select Top 1 EACompl.A_NomeIng      from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc) as NomeIng,
--	(Select Top 1 EAlunos.Nome           from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EALunos.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc) as Nome,
	(Select distinct UMatAlun.CodTur   from UMatAlun(NoLock)  where UMatAlun.MatAluno = (Select Top 1 EACompl.Matricula      from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc))as GradeLevel, 
    (Select Distinct UMatricPl.CodCur  from UMatricPl(NoLock) where UMatricPl.MatAluno = (Select Top 1 EACompl.Matricula      from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc))as CodCur, 
	(Select Distinct UMatricPl.Periodo from UMatricPl(NoLock) where UMatricPl.MatAluno = (Select Top 1 EACompl.Matricula      from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc))as Periodo, 
--	(Select Distinct UMatAlun.CodPer from UMatAlun(NoLock) where UMatAlun.MatAluno = (Select Top 1 EACompl.Matricula      from EACompl(NoLock), EAlunos(NoLock), UMatricPL(NoLock) where UMatricpl.PerLetivo = ZFam.Perletivo and UMatricpl.Status in ('01','07') and EACompl.Matricula = EALunos.Matricula and EACompl.Matricula = UMatricPL.MatAluno and ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2 Order by EAlunos.DTNasc Desc))as CodPer 
	ZFam.Lingua
From ZFamilia ZFam
Left Join EACompl (NoLock) on (ZFam.Nome = EACompl.A_Familia and ZFam.Pessoa1 = EACompl.A_CodPessoa1 and ZFam.Pessoa2 = EACompl.A_CodPessoa2)
Where ZFam.Perletivo = '05/06' and ZFam.Status in ('01','07') -- and Lingua = 'English'
Order by CodCur, Periodo, GradeLevel