/*
	Levantamento de Matrículas (por disciplina)
*/

SELECT UMATRICPL.MATALUNO, COUNT(UMATALUN.MATALUNO) 
	FROM UMATRICPL
	LEFT JOIN UMATALUN ON 
			UMATALUN.MATALUNO = UMATRICPL.MATALUNO AND UMATALUN.PERLETIVO = UMATRICPL.PERLETIVO
WHERE 
	UMATRICPL.STATUS = '01'
	AND UMATRICPL.PERLETIVO = '17/18'
GROUP BY
	UMATRICPL.MATALUNO
ORDER BY 2