Select * from TITMMOV where idmov =31237
SELECT L.DATAEMISSAO,T.IDLAF,L.DOCINI,L.CODCFO, C.NOME,L.VALORCONT,T.CODTRB, T.ALIQTRB,T.VALORTRB
FROM DTRBLAF T, DLAF L, FCFO C 
WHERE T.IDLAF = L.IDLAF 
   AND T.CODTRB = 'ISS'
   AND L.DATAEMISSAO >= '09/01/2007'
   AND C.CODCFO =  L.CODCFO
   AND T.VALORTRB > 0
ORDER BY L.DATAEMISSAO