SELECT 
	L.VALORORIGINAL, 
	T.CODRETENCAO CODRECEITA , L.IDLAN
FROM 
	FLAN L (NOLOCK), 
	FTRBLAN T (NOLOCK) , 
	FRELLAN R (NOLOCK) , 
	FLAN O, 
	DTRIBUTO D (NOLOCK) 
WHERE 
	L.CODCOLIGADA = R.CODCOLIGADA 
AND L.IDLAN = R.IDLANREL 
AND R.CODCOLIGADA = T.CODCOLIGADA 
AND R.IDLAN = T.IDLAN 
AND R.CODCOLIGADA = O.CODCOLIGADA 
AND R.IDLAN = O.IDLAN 
AND T.CODCOLIGADA = D.CODCOLIGADA 
AND T.CODTRB = D.CODTRB 
AND D.TIPOTRIBFISC = L.CLASSIFICACAO 
AND L.CODCOLIGADA = 1 
AND O.DATABAIXA >= '20120716 00:00:00.000' 
AND O.DATABAIXA <= '20120731 00:00:00.000' 
AND L.STATUSLAN <> 2 
AND L.IDFAT IS NULL 
AND T.CODTRB = 'RETIDO' 
AND L.CLASSIFICACAO = 21 
AND L.NFOUDUP = 0 
--GROUP BY T.CODRETENCAO 
--ORDER BY T.CODRETENCAO


