SELECT 
	TMOVRESUMOTRBIT.*,
	(SELECT NOMEFANTASIA FROM FCFO WHERE FCFO.CODCFO = TMOV.CODCFO), TMOV.NUMEROMOV,
	FLAN.DATABAIXA 
FROM 
	TMOVRESUMOTRBIT 
	INNER JOIN TMOV (NOlOCK) ON (TMOV.IDMOV = TMOVRESUMOTRBIT.IDMOV)
	INNER JOIN FLAN (NOLOCK) ON (FLAN.IDMOV = TMOV.IDMOV)
WHERE 
	TMOVRESUMOTRBIT.CODCOLIGADA = 1 
AND TMOVRESUMOTRBIT.CODTRB = 'RETIDO'
AND TMOVRESUMOTRBIT.VALOR > 0
AND FLAN.DATABAIXA BETWEEN '07/01/2012' AND '07/31/2012'