Select 
	CConta.CodConta,
	CConta.Descricao,
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11IH%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11IH%'), 0) as SFIH, --1
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11IM%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11IM%'), 0) as SFIM, --2
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11IE%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11IE%'), 0) as SFIE, --3
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11BH%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11BH%'), 0) as SFBH, --4 
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11BM%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11BM%'), 0) as SFBM, --5
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11BE%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11BE%'), 0) as SFBE, --6
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11SG%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11SG%'), 0) as SFSG, --7
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11ST%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11ST%'), 0) as SFBE, --6
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11SL%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11SL%'), 0) as SFSL, --8
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11SC%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11SC%'), 0) as SFSC, --9
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11SX%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11SX%'), 0) as SFSX, --9
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11AS%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11AS%'), 0) as SFAS, --10
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11AA%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11AA%'), 0) as SFAA, --11
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11AR%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11AR%'), 0) as SFAR, --12
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FF%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FF%'), 0) as SFFF, --13
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FB%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FB%'), 0) as SFFB, --14
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FW%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FW%'), 0) as SFFW, --15
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11Fo%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FO%'), 0) as SFF0, --16
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FJ%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FJ%'), 0) as SFFJ, --16
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FV%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FV%'), 0) as SFFV, --16
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FP%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FP%'), 0) as SFFP, --17
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11FT%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11FT%'), 0) as SFFT, --18
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22IK%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22IK%'), 0) as VSIK, --19
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22BK%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22BK%'), 0) as VSBK, --20
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22SG%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22SG%'), 0) as VSSG, --21
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22ST%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22ST%'), 0) as VSST, --21
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22SL%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22SL%'), 0) as VSSL, --22
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22SC%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22SC%'), 0) as VSSC, --23
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22AS%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22AS%'), 0) as VSAS, --24
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22AA%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22AA%'), 0) as VSAA, --25
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22AR%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22AR%'), 0) as VSAR, --26
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FF%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FF%'), 0) as VSFF, --27
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FB%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FB%'), 0) as VSFB, --28
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FW%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FW%'), 0) as VSFW, --29
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FO%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FO%'), 0) as VSFO, --30
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FJ%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FJ%'), 0) as VSFJ, --30
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FV%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FV%'), 0) as VSFV, --30
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FP%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FP%'), 0) as VSFP, --31
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22FT%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22FT%'), 0) as VSFT, --32
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '41ST%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '41ST%'), 0) as G41ST,
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '41SL%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '41SL%'), 0) as G41SL,
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '42ST%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '42ST%'), 0) as G42ST, 
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '41SC%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '41SC%'), 0) as G41SC, 
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '42SC%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '42SC%'), 0) as G42SC, 
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '61SX%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '61SX%'), 0) as G6SX, --33
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '31FF%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '31FF%'), 0) as G31FF, --33
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '11AD%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '11AD%'), 0) as SFAD, --33
	ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Debito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006' and GCCusto.Codreduzido like '22AD%'), 0) - ISNULL((Select sum(Valor) from CLanca left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto) where CLanca.Credito = CConta.CodConta and Clanca.Data >='08/01/2006' and CLanca.Data <='08/31/2006'and GCCusto.Codreduzido like '22AD%'), 0) as VSAD --33
from 	CConta order by CodConta
Where	CConta.Analitica = '1'
and	CConta.CodConta = '3.1.01.001.0001.0001'





/*
Select GCCusto.Codreduzido ,
	* 
from 	CLanca
	left join GCCusto (NoLock) on (GCCusto.CodCCusto = CLanca.CodCCusto)
	Left join CConta (NoLock) on (CConta.CodConta = CLanca.CREDITO)
Where 	Clanca.Data >='08/01/2006'
and 	CLanca.Data <='08/31/2006'
and 	GCCusto.Codreduzido like '11%'
and	CConta.CodConta = '3.1.01.001.0001.0001'

*/