Select 
	CConta.CodConta, CConta.Reduzido,
	CConta.Descricao,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11IH%'), 0) as ISC_11IH,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11IM%'), 0) as ISC_11IM,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11IE%'), 0) as ISC_11IE, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22IK%'), 0) as ISC_22IK,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22BK%'), 0) as ISC_22BK,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11BH%'), 0) as ISC_11BH, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11BM%'), 0) as ISC_11BM,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11BE%'), 0) as ISC_11BE,
	/* Grupo # I + B */
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11IH%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11IM%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11IE%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22IK%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22BK%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11BH%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11BM%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11BE%'), 0) as Sub_IB,
	/* Grupo S */
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SG%'), 0) as ISC_11SG,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11ST%'), 0) as ISC_11ST,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SL%'), 0) as ISC_11SL, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SC%'), 0) as ISC_11SC,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SX%'), 0) as ISC_11SX,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22SG%'), 0) as ISC_22SG, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22ST%'), 0) as ISC_22ST,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22SL%'), 0) as ISC_22SL, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22SC%'), 0) as ISC_22SC,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '41ST%'), 0) as ISC_41ST,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '41SL%'), 0) as ISC_41SL,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '42ST%'), 0) as ISC_42ST,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '41SC%'), 0) as ISC_41SC,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '42SC%'), 0) as ISC_42SC,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '61SX%'), 0) as ISC_61SX,
	/* Grupo s + */
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SG%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11ST%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SL%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SC%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11SX%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22SG%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22ST%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22SL%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22SC%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '41ST%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '41SL%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '42ST%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '41SC%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '42SC%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '61SX%'), 0) as Sub_S,
	/* Grupo A e F*/
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AS%'), 0) as ISC_11AS,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AA%'), 0) as ISC_11AA,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AR%'), 0) as ISC_11AR,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AD%'), 0) as ISC_11AD,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AS%'), 0) as ISC_22AS,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AA%'), 0) as ISC_22AA,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AR%'), 0) as ISC_22AR,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AD%'), 0) as ISC_22AD, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FF%'), 0) as ISC_11FF,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FB%'), 0) as ISC_11FB,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FW%'), 0) as ISC_11FW,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FO%'), 0) as ISC_11FO,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FJ%'), 0) as ISC_11FJ,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FV%'), 0) as ISC_11FV,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FP%'), 0) as ISC_11FP,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FT%'), 0) as ISC_11FT,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FF%'), 0) as ISC_22FF,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FB%'), 0) as ISC_22FB, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FW%'), 0) as ISC_22FW,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FO%'), 0) as ISC_22FO, 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FJ%'), 0) as ISC_22FJ,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FV%'), 0) as ISC_22FV,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FP%'), 0) as ISC_22FP,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FT%'), 0) as ISC_22FT,
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '31FF%'), 0) as ISC_31FF,
	/* Grupo A + F */ 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AS%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AA%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AR%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11AD%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AS%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AA%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AR%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22AD%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FF%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FB%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FW%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FO%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FJ%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FV%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FP%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '11FT%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FF%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FB%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FW%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FO%'), 0) + 
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FJ%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FV%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FP%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '22FT%'), 0) +
	ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and GCCusto.CodReduzido like '31FF%'), 0) as Sub_AF,
	ISNULL((Select Sum(Valor) from CLanca where CLanca.Debito = CConta.CodConta and CLanca.Data >='09/01/2006' and CLanca.Data <='09/30/2006'),0) as Debito,
	ISNULL((Select Sum(Valor) from CLanca where CLanca.Credito = CConta.CodConta and CLanca.Data >='09/01/2006' and CLanca.Data <='09/30/2006'),0) as Credito
from 	CConta Order by CodConta
--Where	CConta.Analitica = '1'
--and	CConta.CodConta = '1.3.01.001.0001.0001'
--ISNULL((Select sum(VLRDebito) - Sum(VLRCredito) from CRateiolc where CRateiolc.Data >='09/01/2006' and CRateiolc.Data <='09/30/2006' and CRateioLc.CodConta = CConta.CodConta and CRateiolc.CodGerencial like '1.01.01.01.02%'), 0) as ISC_11IM,