Select 
	CConta.CodConta, CConta.Reduzido,
	CConta.Descricao,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11IH%') as ISC_11IH,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11IM%') as ISC_11IM,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11IE%') as ISC_11IE, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22IK%') as ISC_22IK,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22BK%') as ISC_22BK,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11BH%') as ISC_11BH, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11BM%') as ISC_11BM,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11BE%') as ISC_11BE,
	/* Grupo # I + B */
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11IH%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11IM%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11IE%'), 0) + 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22IK%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22BK%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11BH%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11BM%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11BE%'), 0) as Sub_IB,
	/* Grupo S */
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SG%') as ISC_11SG,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11ST%') as ISC_11ST,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SL%') as ISC_11SL, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SC%') as ISC_11SC,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SX%') as ISC_11SX,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22SG%') as ISC_22SG, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22ST%') as ISC_22ST,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22SL%') as ISC_22SL, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22SC%') as ISC_22SC,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '41ST%') as ISC_41ST,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '41SL%') as ISC_41SL,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '42ST%') as ISC_42ST,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '41SC%') as ISC_41SC,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '42SC%') as ISC_42SC,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '61SX%') as ISC_61SX,
	/* Grupo s + */
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SG%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11ST%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SL%'), 0) + 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SC%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11SX%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22SG%'), 0) + 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22ST%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22SL%'), 0) + 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22SC%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '41ST%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '41SL%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '42ST%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '41SC%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '42SC%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '61SX%'), 0) as Sub_S,
	/* Grupo A e F*/
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AS%') as ISC_11AS,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AA%') as ISC_11AA,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AR%') as ISC_11AR,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AD%') as ISC_11AD,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AS%') as ISC_22AS,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AA%') as ISC_22AA,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AR%') as ISC_22AR,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AD%') as ISC_22AD,
	/* Grupo A */ 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AS%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AA%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AR%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11AD%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AS%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AA%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AR%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22AD%'), 0) as Sub_A,
	/* Grupo F */
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FF%') as ISC_11FF,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FB%') as ISC_11FB,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FW%') as ISC_11FW,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FO%') as ISC_11FO,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FJ%') as ISC_11FJ,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FV%') as ISC_11FV,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FP%') as ISC_11FP,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FT%') as ISC_11FT,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FF%') as ISC_22FF,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FB%') as ISC_22FB, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FW%') as ISC_22FW,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FO%') as ISC_22FO, 
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FJ%') as ISC_22FJ,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FV%') as ISC_22FV,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FP%') as ISC_22FP,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FT%') as ISC_22FT,
	(Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '31FF%') as ISC_31FF,
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FF%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FB%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FW%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FO%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FJ%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FV%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FP%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '11FT%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FF%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FB%'), 0) + 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FW%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FO%'), 0) + 
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FJ%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FV%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FP%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '22FT%'), 0) +
	ISNULL((Select Sum(VLRDebito) - Sum(VLRCredito) from CRateiolc left join GCCusto (NoLock) on (GCCusto.CodCCusto = CRateiolc.CodGerencial) where CRateiolc.CodConta = CConta.CodConta and CRateiolc.Data >=:PLN_$B$1_D and CRateiolc.Data <=:PLN_$B$2_D and GCCusto.CodReduzido like '31FF%'), 0) as Sub_AF,
	ISNULL((Select Sum(Valor) from CLanca where CLanca.Debito = CConta.CodConta and CLanca.Data >=:PLN_$B$1_D and CLanca.Data <='09/30/2006'),0) as Debito,
	ISNULL((Select Sum(Valor) from CLanca where CLanca.Credito = CConta.CodConta and CLanca.Data >=:PLN_$B$1_D and CLanca.Data <='09/30/2006'),0) as Credito
from 	CConta 
Order by  CodConta
