/*EXTRATO - PTA*/

Select 
IDLAN,
DATABAIXA,
(SELECT NOMEFANTASIA FROM FCFO WHERE FCFO.CODCFO = FLAN.CODCFO) AS FORNECEDOR,
HISTORICO, VALORBAIXADO + isnull(VALORADIANTAMENTO,0) + Case when idlan = 198843 then VALORADIANTAMENTO * - 1 else 0 end from FLAN where
CODTDO in (Select CODTDO from FTDOCONT where CODCONTA = (Select CODCONTA from CCONTA where REDUZIDO = 176 and CCONTA.CODCONTA NOT LIKE '1.1.03%'))
and DATABAIXA between '07-31-2016' and GETDATE()
and PAGREC = 1

UNION

Select
IDLAN, 
DATABAIXA,
(SELECT NOMEFANTASIA FROM FCFO WHERE FCFO.CODCFO = FLAN.CODCFO) AS FORNECEDOR,
HISTORICO, (VALORBAIXADO + isnull(VALORADIANTAMENTO,0)) * -1 
+ case when CODTB2FLX = '002' then VALORORIGINAL * -1
else 0 end 
from FLAN where
CODTDO in (Select CODTDO from FTDOCONT where CODCONTA = (Select CODCONTA from CCONTA where REDUZIDO = 176 and CCONTA.CODCONTA NOT LIKE '1.1.03%'))
and DATABAIXA between '07-31-2016' and GETDATE()
and PAGREC = 2
ORDER BY DATABAIXA