


Select 
	FCFO.NOMEFANTASIA,
	TPRODUTO.NOMEFANTASIA,
	*
from	
	TITMMOV 
INNER JOIN TMOV (NOLOCK) ON (TMOV.IDMOV = TITMMOV.IDMOV)
INNER JOIN FCFO (NOLOCK) ON (FCFO.CODCFO = TMOV.CODCFO)
INNER JOIN TPRODUTO (NOLOCK) ON (TPRODUTO.IDPRD = TITMMOV.IDPRD)
WHERE 
	TMOV.DATAEMISSAO BETWEEN '09/01/2014' AND '09/30/2014' 
AND TITMMOV.CODTB2FAT = '01.04.001'
AND TMOV.CODTMV IN ('1.1.06', '1.2.01', '1.2.10')