/*
select VALOR, CREDITO, DEBITO, * from CPARTIDA where 
	CPARTIDA.DATA >= '08-01-2016'
	--CPARTIDA.CODHISTP not in (Select CODHISTP from CHISTP where HISTFECHA = 1) 
	--CPARTIDA.CREDITO = '4.1.02.001.0001'
*/

/* DIMENSÃO -  PLANO DE CONTAS - DASHBOARD */
SELECT 
	CCONTA.CODCONTA, CCONTA.REDUZIDO, CCONTA.DESCRICAO, CCONTA.ANALITICA, CPCCOMPL.ORCAMENTO, CCONTA.INATIVA
FROM 
	CCONTA
	JOIN CPCCOMPL ON CPCCOMPL.CODCONTA = CCONTA.CODCONTA
--WHERE 
	--CCONTA.CODCONTA >= '3' AND CCONTA.CODCONTA < '5'

