IF EXISTS (SELECT * 
	   FROM   sysobjects 
	   WHERE  
	   name = 'ATUALIZA_EMAIL_NA_GUSUARIO' AND
  	   type = 'TR')
    DROP TRIGGER ATUALIZA_EMAIL_NA_GUSUARIO
GO

CREATE TRIGGER ATUALIZA_EMAIL_NA_GUSUARIO
ON PPESSOA
FOR INSERT, UPDATE
AS 
BEGIN
	UPDATE GUSUARIO SET GUSUARIO.EMAIL = PPESSOA.EMAIL
	FROM
		PPESSOA, GUSUARIO
	WHERE 
		PPESSOA.CODUSUARIO = GUSUARIO.CODUSUARIO
END