IF EXISTS (SELECT * 
	   FROM   sysobjects 
	   WHERE  
	   name = 'ATUALIZA_EMAIL_DE_PROFESSORES_NA_GUSUARIO' AND
  	   type = 'TR')
    DROP TRIGGER ATUALIZA_EMAIL_DE_PROFESSORES_NA_GUSUARIO
GO

CREATE TRIGGER ATUALIZA_EMAIL_DE_PROFESSORES_NA_GUSUARIO
ON EPROFES
FOR INSERT, UPDATE
AS 
BEGIN
	UPDATE PPESSOA SET PPESSOA.CODUSUARIO = EPROFES.CODUSUARIO
	FROM
		PPESSOA, EPROFES
	WHERE 
		PPESSOA.CODIGO = EPROFES.CODPESSOA

END
GO
