CREATE TABLE ZMECRELNACIONALIDADES (
	PERLETIVO    VARCHAR(6)   NOT NULL,
	CODIGO       VARCHAR(20)  NOT NULL,
	DESCRICAO    VARCHAR(255) NULL,
	CODIGOMEC    VARCHAR(20)  NOT NULL,
	DESCCOMPLETA VARCHAR(255) NULL,
CONSTRAINT PKZMECRELNACIONALIDADES PRIMARY KEY(PERLETIVO, CODIGO))
GO

CREATE TABLE ZMECRELORGAOEMISSOR (
	PERLETIVO    VARCHAR(6)   NOT NULL,
	ORGAO        VARCHAR(20)  NOT NULL,
	CODIGOMEC    INTEGER      NOT NULL,
	DESCCOMPLETA VARCHAR(255) NULL,
CONSTRAINT PKZMECRELORGAOEMISSOR PRIMARY KEY(PERLETIVO, ORGAO))
GO

CREATE TABLE ZMECRELESCOLARIDADE (
	PERLETIVO    VARCHAR(6)   NOT NULL,
	CODIGO       VARCHAR(20)  NOT NULL,
	CODIGOMEC    INTEGER      NOT NULL,
	DESCCOMPLETA VARCHAR(255) NULL,
CONSTRAINT PKZMECRELESCOLARIDADE PRIMARY KEY(PERLETIVO, CODIGO))
GO

CREATE TABLE ZMECRELCURSOSETAPAS (
	PERLETIVO    VARCHAR(6)   NOT NULL,
	CURSO        INTEGER      NOT NULL,
	PERIODO      INTEGER      NOT NULL,
	CODIGOMEC    INTEGER      NOT NULL,
	SERIEMEC     INTEGER      NULL,
	CONCLUINTE   INTEGER      NULL,
	MODALIDADE   INTEGER      NOT NULL,
	EJA          INTEGER      NULL,
	TIPOMULTI    INTEGER      NULL,
	TIPOFLUXO    INTEGER      NULL,
	TIPOUNI      INTEGER      NULL,
	DESCCOMPLETA VARCHAR(255) NULL,
CONSTRAINT PKZMECRELCURSOSETAPAS PRIMARY KEY(PERLETIVO, CURSO, PERIODO))
GO

CREATE TABLE ZMECRELDISCIPLINAS (
	PERLETIVO    VARCHAR(6)   NOT NULL,
	CODMAT       VARCHAR(16)  NOT NULL,
	CODIGOMEC    INTEGER      NOT NULL,
	DESCCOMPLETA VARCHAR(255) NULL,
CONSTRAINT PKZMECRELZMECRELDISCIPLINAS PRIMARY KEY(PERLETIVO, CODMAT))
GO

/* ************************************************************************************* */

ALTER TABLE ZEPROFESMEC
ADD LICENCIATURA1 INTEGER
GO
ALTER TABLE ZEPROFESMEC
ADD FORMACAOSUPERIOR1 VARCHAR(6)
GO
ALTER TABLE ZEPROFESMEC
ADD ANOCONCLUSAOSUPERIOR1 VARCHAR(4)
GO
ALTER TABLE ZEPROFESMEC
ADD TIPOINSTSUPERIOR1 INTEGER
GO
ALTER TABLE ZEPROFESMEC
ADD INSTITUICAOSUPERIOR1 VARCHAR(7)
GO

ALTER TABLE ZEPROFESMEC
ADD LICENCIATURA2 INTEGER
GO
ALTER TABLE ZEPROFESMEC
ADD FORMACAOSUPERIOR2 VARCHAR(6)
GO
ALTER TABLE ZEPROFESMEC
ADD ANOCONCLUSAOSUPERIOR2 VARCHAR(4)
GO
ALTER TABLE ZEPROFESMEC
ADD TIPOINSTSUPERIOR2 INTEGER
GO
ALTER TABLE ZEPROFESMEC
ADD INSTITUICAOSUPERIOR2 VARCHAR(7)
GO

ALTER TABLE ZEPROFESMEC
ADD LICENCIATURA3 INTEGER
GO
ALTER TABLE ZEPROFESMEC
ADD FORMACAOSUPERIOR3 VARCHAR(6)
GO
ALTER TABLE ZEPROFESMEC
ADD ANOCONCLUSAOSUPERIOR3 VARCHAR(4)
GO
ALTER TABLE ZEPROFESMEC
ADD TIPOINSTSUPERIOR3 INTEGER
GO
ALTER TABLE ZEPROFESMEC
ADD INSTITUICAOSUPERIOR3 VARCHAR(7)
GO