
ALTER TABLE ZEPROFESMEC ADD PORTARIANATURALIZACAO VARCHAR(15)
GO
ALTER TABLE ZEPROFESMEC ADD FORMACAOSUPERIOR INTEGER
GO
ALTER TABLE ZEPROFESMEC ADD POSGRADUACAO INTEGER
GO
ALTER TABLE ZETURMASMEC ADD D1 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D2 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D3 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D4 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D5 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D6 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D7 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D8 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D9 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D10 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D11 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D12 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D13 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D14 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D15 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D16 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D17 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D18 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D19 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D20 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D21 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D22 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D23 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD D24 SMALLINT
GO
ALTER TABLE ZETURMASMEC ADD INEP VARCHAR(20)
GO
ALTER TABLE ZEPROFESMEC ADD D1 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D2 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D3 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D4 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D5 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D6 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D7 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D8 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D9 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D10 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D11 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D12 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD D13 SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD CRECHE SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD PREESCOLA SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD NECESSEDUESPECIAIS SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD EDUINDIGENA SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD INTERDIVERSOUTROS SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD NENHUM SMALLINT
GO
ALTER TABLE ZEPROFESMEC ADD INEP VARCHAR(20)
GO
ALTER TABLE ZEALUNOSMEC ADD CEGUEIRA SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD BAIXAVISAO SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD SURDEZ SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD DEFICIENCIAAUDITIVA SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD SURDOCEGUEIRA SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD DEFICIENCIAFISICA SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD DEFICIENCIAMENTAL SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD TRANSINVASDESENVOLV SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD SINDROMEDOWN SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD DEFICIENCIAMULTIPLA SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD SUPERDOTADO SMALLINT
GO
ALTER TABLE ZEALUNOSMEC ADD INEP VARCHAR(20)

CREATE TABLE ZEPROFESMEC_TEMP (
	CODPROF			VARCHAR(10) NOT NULL,
	NIS			INTEGER,
	TIPOLOGRADOURO		VARCHAR(3),
	NACIONALIDADE		VARCHAR(3),
	DATAENTRADA		DATETIME,
	CERTIDAOCIVIL		SMALLINT,
	TIPOCERTIDAOCIVIL	SMALLINT,
	NUMTERMO		INTEGER,
	FOLHA			VARCHAR(4),
	LIVRO			VARCHAR(8),
	DATAEMISSAO		DATETIME,
	UFCARTORIO		VARCHAR(2),
	NOMECARTORIO		VARCHAR(20),
	ORGAOEMISSOR		INTEGER,
	FUNCAODOCENTE		SMALLINT,
	FUNCAOAUXILIAR		SMALLINT,
	ESCOLARIDADE		INTEGER,
	ETAPAFUNDAMENTAL1A4	SMALLINT,
	ETAPAFUNDAMENTAL5A8	SMALLINT,
	ETAPAFUNDAMENTAL1A5	SMALLINT,
	ETAPAFUNDAMENTAL6A9	SMALLINT,
	ETAPAINTEGRADO		SMALLINT,
	ETAPAEDUCESPECIAL	SMALLINT,
	ETAPAEDUCJOVENS1A4	SMALLINT,
	ETAPAEDUCJOVENS5A8	SMALLINT,
	ETAPAEDUCJOVENSADULTO	SMALLINT,
	ETAPAEDUCJOVENSPROFIS	SMALLINT,
	NEES			SMALLINT,
	PORTARIANATURALIZACAO 	VARCHAR(15),
	FORMACAOSUPERIOR 	INTEGER,
	POSGRADUACAO 		INTEGER,
	D1			SMALLINT,
	D2			SMALLINT,
	D3			SMALLINT,
	D4			SMALLINT,
	D5			SMALLINT,
	D6			SMALLINT,
	D7			SMALLINT,
	D8			SMALLINT,
	D9			SMALLINT,
	D10			SMALLINT,
	D11			SMALLINT,
	D12			SMALLINT,
	D13			SMALLINT,
	CRECHE			SMALLINT,
	PREESCOLA		SMALLINT,
	NECESSEDUESPECIAIS	SMALLINT,
	EDUINDIGENA		SMALLINT,
	INTERDIVERSOUTROS	SMALLINT,
	NENHUM			SMALLINT,
        INEP                    VARCHAR(20))
GO
		
INSERT INTO ZEPROFESMEC_TEMP (CODPROF,NIS,TIPOLOGRADOURO,
NACIONALIDADE,DATAENTRADA,CERTIDAOCIVIL,TIPOCERTIDAOCIVIL,
NUMTERMO,FOLHA,LIVRO,DATAEMISSAO,UFCARTORIO,NOMECARTORIO,
ORGAOEMISSOR,FUNCAODOCENTE,FUNCAOAUXILIAR,ESCOLARIDADE,
ETAPAFUNDAMENTAL1A4,ETAPAFUNDAMENTAL5A8,ETAPAFUNDAMENTAL1A5,
ETAPAFUNDAMENTAL6A9,ETAPAINTEGRADO,ETAPAEDUCESPECIAL,
ETAPAEDUCJOVENS1A4,ETAPAEDUCJOVENS5A8,ETAPAEDUCJOVENSADULTO,
ETAPAEDUCJOVENSPROFIS,NEES,PORTARIANATURALIZACAO,FORMACAOSUPERIOR,
POSGRADUACAO,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,CRECHE,
PREESCOLA,NECESSEDUESPECIAIS,EDUINDIGENA,INTERDIVERSOUTROS,NENHUM,INEP)
SELECT CODPROF,NIS,TIPOLOGRADOURO,
NACIONALIDADE,DATAENTRADA,CERTIDAOCIVIL,TIPOCERTIDAOCIVIL,
NUMTERMO,FOLHA,LIVRO,DATAEMISSAO,UFCARTORIO,NOMECARTORIO,
ORGAOEMISSOR,FUNCAODOCENTE,FUNCAOAUXILIAR,ESCOLARIDADE,
ETAPAFUNDAMENTAL1A4,ETAPAFUNDAMENTAL5A8,ETAPAFUNDAMENTAL1A5,
ETAPAFUNDAMENTAL6A9,ETAPAINTEGRADO,ETAPAEDUCESPECIAL,
ETAPAEDUCJOVENS1A4,ETAPAEDUCJOVENS5A8,ETAPAEDUCJOVENSADULTO,
ETAPAEDUCJOVENSPROFIS,NEES,PORTARIANATURALIZACAO,FORMACAOSUPERIOR,
POSGRADUACAO,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,CRECHE,
PREESCOLA,NECESSEDUESPECIAIS,EDUINDIGENA,INTERDIVERSOUTROS,NENHUM,INEP
FROM ZEPROFESMEC
GO

DROP TABLE ZEPROFESMEC
GO

CREATE TABLE ZEPROFESMEC (
	CODPROF			VARCHAR(10) NOT NULL,
	NIS			INTEGER,
	TIPOLOGRADOURO		VARCHAR(3),
	NACIONALIDADE		VARCHAR(3),
	DATAENTRADA		DATETIME,
	CERTIDAOCIVIL		SMALLINT,
	TIPOCERTIDAOCIVIL	SMALLINT,
	NUMTERMO		INTEGER,
	FOLHA			VARCHAR(4),
	LIVRO			VARCHAR(8),
	DATAEMISSAO		DATETIME,
	UFCARTORIO		VARCHAR(2),
	NOMECARTORIO		VARCHAR(20),
	ORGAOEMISSOR		INTEGER,
	FUNCAODOCENTE		SMALLINT,
	FUNCAOAUXILIAR		SMALLINT,
	ESCOLARIDADE		INTEGER,
	ETAPAFUNDAMENTAL1A4	SMALLINT,
	ETAPAFUNDAMENTAL5A8	SMALLINT,
	ETAPAFUNDAMENTAL1A5	SMALLINT,
	ETAPAFUNDAMENTAL6A9	SMALLINT,
	ETAPAINTEGRADO		SMALLINT,
	ETAPAEDUCESPECIAL	SMALLINT,
	ETAPAEDUCJOVENS1A4	SMALLINT,
	ETAPAEDUCJOVENS5A8	SMALLINT,
	ETAPAEDUCJOVENSADULTO	SMALLINT,
	ETAPAEDUCJOVENSPROFIS	SMALLINT,
	NEES			SMALLINT,
	PORTARIANATURALIZACAO 	VARCHAR(15),
	FORMACAOSUPERIOR 	INTEGER,
	POSGRADUACAO 		INTEGER,
	D1			SMALLINT,
	D2			SMALLINT,
	D3			SMALLINT,
	D4			SMALLINT,
	D5			SMALLINT,
	D6			SMALLINT,
	D7			SMALLINT,
	D8			SMALLINT,
	D9			SMALLINT,
	D10			SMALLINT,
	D11			SMALLINT,
	D12			SMALLINT,
	D13			SMALLINT,
	CRECHE			SMALLINT,
	PREESCOLA		SMALLINT,
	NECESSEDUESPECIAIS	SMALLINT,
	EDUINDIGENA		SMALLINT,
	INTERDIVERSOUTROS	SMALLINT,
	NENHUM			SMALLINT,
	INEP                    VARCHAR(20),
CONSTRAINT PKZEPROFESMEC PRIMARY KEY (CODPROF))
GO

INSERT INTO ZEPROFESMEC (CODPROF,NIS,TIPOLOGRADOURO,
NACIONALIDADE,DATAENTRADA,CERTIDAOCIVIL,TIPOCERTIDAOCIVIL,
NUMTERMO,FOLHA,LIVRO,DATAEMISSAO,UFCARTORIO,NOMECARTORIO,
ORGAOEMISSOR,FUNCAODOCENTE,FUNCAOAUXILIAR,ESCOLARIDADE,
ETAPAFUNDAMENTAL1A4,ETAPAFUNDAMENTAL5A8,ETAPAFUNDAMENTAL1A5,
ETAPAFUNDAMENTAL6A9,ETAPAINTEGRADO,ETAPAEDUCESPECIAL,
ETAPAEDUCJOVENS1A4,ETAPAEDUCJOVENS5A8,ETAPAEDUCJOVENSADULTO,
ETAPAEDUCJOVENSPROFIS,NEES,PORTARIANATURALIZACAO,FORMACAOSUPERIOR,
POSGRADUACAO,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,CRECHE,
PREESCOLA,NECESSEDUESPECIAIS,EDUINDIGENA,INTERDIVERSOUTROS,NENHUM,INEP)
SELECT CODPROF,NIS,TIPOLOGRADOURO,
NACIONALIDADE,DATAENTRADA,CERTIDAOCIVIL,TIPOCERTIDAOCIVIL,
NUMTERMO,FOLHA,LIVRO,DATAEMISSAO,UFCARTORIO,NOMECARTORIO,
ORGAOEMISSOR,FUNCAODOCENTE,FUNCAOAUXILIAR,ESCOLARIDADE,
ETAPAFUNDAMENTAL1A4,ETAPAFUNDAMENTAL5A8,ETAPAFUNDAMENTAL1A5,
ETAPAFUNDAMENTAL6A9,ETAPAINTEGRADO,ETAPAEDUCESPECIAL,
ETAPAEDUCJOVENS1A4,ETAPAEDUCJOVENS5A8,ETAPAEDUCJOVENSADULTO,
ETAPAEDUCJOVENSPROFIS,NEES,PORTARIANATURALIZACAO,FORMACAOSUPERIOR,
POSGRADUACAO,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,CRECHE,
PREESCOLA,NECESSEDUESPECIAIS,EDUINDIGENA,INTERDIVERSOUTROS,NENHUM,INEP
FROM ZEPROFESMEC_TEMP
GO

DROP TABLE ZEPROFESMEC_TEMP
GO

CREATE TABLE ZETURMASMEC_TEMP (
	CODCOLIGADA 	DCODCOLIGADA,
	CODFILIAL 	SMALLINT NOT NULL,
	CODPERLET 	VARCHAR(6) NOT NULL,
	CODCUR 		INT NOT NULL,
	CODPER 		INT NOT NULL,
	CODTUN 		INT NOT NULL,
	CODTUR 		VARCHAR(16) NOT NULL,
	MODALIDADE	SMALLINT,
	EJA		INTEGER,
	ETAPA		INTEGER,
	TIPOMULTI	SMALLINT,
	TIPOFLUXO	SMALLINT,
	TIPOUNI		SMALLINT,
	CURSO		VARCHAR(7),
	SERIE		INTEGER,
	D1		SMALLINT,
	D2		SMALLINT,
	D3		SMALLINT,
	D4		SMALLINT,
	D5		SMALLINT,
	D6		SMALLINT,
	D7		SMALLINT,
	D8		SMALLINT,
	D9		SMALLINT,
	D10		SMALLINT,
	D11		SMALLINT,
	D12		SMALLINT,
	D13		SMALLINT,
	D14		SMALLINT,
	D15		SMALLINT,
	D16		SMALLINT,
	D17		SMALLINT,
	D18		SMALLINT,
	D19		SMALLINT,
	D20		SMALLINT,
	D21		SMALLINT,
	D22		SMALLINT,
	D23		SMALLINT,
	D24		SMALLINT,
	INEP            VARCHAR(20))
GO

INSERT INTO ZETURMASMEC_TEMP (CODCOLIGADA,CODFILIAL,CODPERLET,CODCUR,
CODPER,CODTUN,CODTUR,MODALIDADE,EJA,ETAPA,TIPOMULTI,TIPOFLUXO,
TIPOUNI,CURSO,SERIE,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,
D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,INEP)
SELECT CODCOLIGADA,CODFILIAL,CODPERLET,CODCUR,
CODPER,CODTUN,CODTUR,MODALIDADE,EJA,ETAPA,TIPOMULTI,TIPOFLUXO,
TIPOUNI,CURSO,SERIE,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,
D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,INEP
FROM ZETURMASMEC
GO

DROP TABLE ZETURMASMEC
GO

CREATE TABLE ZETURMASMEC (
	CODCOLIGADA 	DCODCOLIGADA,
	CODFILIAL 	SMALLINT NOT NULL,
	CODPERLET 	VARCHAR(6) NOT NULL,
	CODCUR 		INT NOT NULL,
	CODPER 		INT NOT NULL,
	CODTUN 		INT NOT NULL,
	CODTUR 		VARCHAR(16) NOT NULL,
	MODALIDADE	SMALLINT,
	EJA		INTEGER,
	ETAPA		INTEGER,
	TIPOMULTI	SMALLINT,
	TIPOFLUXO	SMALLINT,
	TIPOUNI		SMALLINT,
	CURSO		VARCHAR(7),
	SERIE		INTEGER,
	D1		SMALLINT,
	D2		SMALLINT,
	D3		SMALLINT,
	D4		SMALLINT,
	D5		SMALLINT,
	D6		SMALLINT,
	D7		SMALLINT,
	D8		SMALLINT,
	D9		SMALLINT,
	D10		SMALLINT,
	D11		SMALLINT,
	D12		SMALLINT,
	D13		SMALLINT,
	D14		SMALLINT,
	D15		SMALLINT,
	D16		SMALLINT,
	D17		SMALLINT,
	D18		SMALLINT,
	D19		SMALLINT,
	D20		SMALLINT,
	D21		SMALLINT,
	D22		SMALLINT,
	D23		SMALLINT,
	D24		SMALLINT,
	INEP            VARCHAR(20),
CONSTRAINT PKZETURMASMEC PRIMARY KEY (CODCOLIGADA,CODFILIAL,CODPERLET,CODCUR,CODPER,CODTUN,CODTUR))
GO

INSERT INTO ZETURMASMEC (CODCOLIGADA,CODFILIAL,CODPERLET,CODCUR,
CODPER,CODTUN,CODTUR,MODALIDADE,EJA,ETAPA,TIPOMULTI,TIPOFLUXO,
TIPOUNI,CURSO,SERIE,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,
D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,INEP)
SELECT CODCOLIGADA,CODFILIAL,CODPERLET,CODCUR,
CODPER,CODTUN,CODTUR,MODALIDADE,EJA,ETAPA,TIPOMULTI,TIPOFLUXO,
TIPOUNI,CURSO,SERIE,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,
D13,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23,D24,INEP
FROM ZETURMASMEC_TEMP
GO

DROP TABLE ZETURMASMEC_TEMP
GO

CREATE TABLE ZEALUNOSMEC_TEMP (
	CODCOLIGADA 		DCODCOLIGADA,
	MATRICULA 		VARCHAR(10) NOT NULL,
	CODFILIAL		SMALLINT NOT NULL,
	PERLETIVO		VARCHAR(6) NOT NULL,
	CODCUR			INTEGER NOT NULL,
	CODPER			INTEGER NOT NULL,
	CODTUN			INTEGER NOT NULL,
	CODTUR			VARCHAR(16) NOT NULL,
	NIS			INTEGER,
	TIPOLOGRADOURO		VARCHAR(3),
	NACIONALIDADE		VARCHAR(3),
	DATAENTRADA		DATETIME,
	ORGAOEMISSOR		INTEGER,
	DATAINGRESSO		DATETIME,
	CURSOENSINOMEDIO	SMALLINT,
	NECESPECIAIS		SMALLINT,
	TIPONECESPECIAIS	SMALLINT,
	ALUNOCLASSECOMUM	SMALLINT,
	APOIOPEDAGOGICO		SMALLINT,
	CORRECAOFLUXO		INTEGER,
	BOLSAFAMILIA		SMALLINT,
	TURMAUNIFICADA		SMALLINT,
	TURMAMULTI		INTEGER,
	TRANSPPUBLICO		SMALLINT,
	TRANSPOFERECIDO		SMALLINT,
	ZONARESIDENCIA		SMALLINT,
	CONCLUINTE		SMALLINT,
	ADMITIDOCENSO		SMALLINT,
	CEGUEIRA		SMALLINT,
	BAIXAVISAO		SMALLINT,
	SURDEZ			SMALLINT,
	DEFICIENCIAAUDITIVA	SMALLINT,
	SURDOCEGUEIRA		SMALLINT,
	DEFICIENCIAFISICA	SMALLINT,
	DEFICIENCIAMENTAL	SMALLINT,
	TRANSINVASDESENVOLV	SMALLINT,
	SINDROMEDOWN		SMALLINT,
	DEFICIENCIAMULTIPLA	SMALLINT,
	SUPERDOTADO		SMALLINT,
        INEP                    VARCHAR(20))
GO

INSERT INTO ZEALUNOSMEC_TEMP (CODCOLIGADA,MATRICULA,CODFILIAL,PERLETIVO,
CODCUR,CODPER,CODTUN,CODTUR,NIS,TIPOLOGRADOURO,NACIONALIDADE,DATAENTRADA,
ORGAOEMISSOR,DATAINGRESSO,CURSOENSINOMEDIO,NECESPECIAIS,TIPONECESPECIAIS,
ALUNOCLASSECOMUM,APOIOPEDAGOGICO,CORRECAOFLUXO,BOLSAFAMILIA,TURMAUNIFICADA,
TURMAMULTI,TRANSPPUBLICO,TRANSPOFERECIDO,ZONARESIDENCIA,CONCLUINTE,
ADMITIDOCENSO,CEGUEIRA,BAIXAVISAO,SURDEZ,DEFICIENCIAAUDITIVA,SURDOCEGUEIRA,
DEFICIENCIAFISICA,DEFICIENCIAMENTAL,TRANSINVASDESENVOLV,SINDROMEDOWN,
DEFICIENCIAMULTIPLA,SUPERDOTADO,INEP)
SELECT CODCOLIGADA,MATRICULA,CODFILIAL,PERLETIVO,
CODCUR,CODPER,CODTUN,CODTUR,NIS,TIPOLOGRADOURO,NACIONALIDADE,DATAENTRADA,
ORGAOEMISSOR,DATAINGRESSO,CURSOENSINOMEDIO,NECESPECIAIS,TIPONECESPECIAIS,
ALUNOCLASSECOMUM,APOIOPEDAGOGICO,CORRECAOFLUXO,BOLSAFAMILIA,TURMAUNIFICADA,
TURMAMULTI,TRANSPPUBLICO,TRANSPOFERECIDO,ZONARESIDENCIA,CONCLUINTE,
ADMITIDOCENSO,CEGUEIRA,BAIXAVISAO,SURDEZ,DEFICIENCIAAUDITIVA,SURDOCEGUEIRA,
DEFICIENCIAFISICA,DEFICIENCIAMENTAL,TRANSINVASDESENVOLV,SINDROMEDOWN,
DEFICIENCIAMULTIPLA,SUPERDOTADO,INEP
FROM ZEALUNOSMEC
GO

DROP TABLE ZEALUNOSMEC
GO

CREATE TABLE ZEALUNOSMEC (
	CODCOLIGADA 		DCODCOLIGADA,
	MATRICULA 		VARCHAR(10) NOT NULL,
	CODFILIAL		SMALLINT NOT NULL,
	PERLETIVO		VARCHAR(6) NOT NULL,
	CODCUR			INTEGER NOT NULL,
	CODPER			INTEGER NOT NULL,
	CODTUN			INTEGER NOT NULL,
	CODTUR			VARCHAR(16) NOT NULL,
	NIS			INTEGER,
	TIPOLOGRADOURO		VARCHAR(3),
	NACIONALIDADE		VARCHAR(3),
	DATAENTRADA		DATETIME,
	ORGAOEMISSOR		INTEGER,
	DATAINGRESSO		DATETIME,
	CURSOENSINOMEDIO	SMALLINT,
	NECESPECIAIS		SMALLINT,
	TIPONECESPECIAIS	SMALLINT,
	ALUNOCLASSECOMUM	SMALLINT,
	APOIOPEDAGOGICO		SMALLINT,
	CORRECAOFLUXO		INTEGER,
	BOLSAFAMILIA		SMALLINT,
	TURMAUNIFICADA		SMALLINT,
	TURMAMULTI		INTEGER,
	TRANSPPUBLICO		SMALLINT,
	TRANSPOFERECIDO		SMALLINT,
	ZONARESIDENCIA		SMALLINT,
	CONCLUINTE		SMALLINT,
	ADMITIDOCENSO		SMALLINT,
	CEGUEIRA		SMALLINT,
	BAIXAVISAO		SMALLINT,
	SURDEZ			SMALLINT,
	DEFICIENCIAAUDITIVA	SMALLINT,
	SURDOCEGUEIRA		SMALLINT,
	DEFICIENCIAFISICA	SMALLINT,
	DEFICIENCIAMENTAL	SMALLINT,
	TRANSINVASDESENVOLV	SMALLINT,
	SINDROMEDOWN		SMALLINT,
	DEFICIENCIAMULTIPLA	SMALLINT,
	SUPERDOTADO		SMALLINT,
	INEP                    VARCHAR(20),
CONSTRAINT PKZEALUNOSMEC PRIMARY KEY (CODCOLIGADA, MATRICULA, PERLETIVO, CODFILIAL, CODCUR, CODPER, CODTUN, CODTUR))
GO

INSERT INTO ZEALUNOSMEC (CODCOLIGADA,MATRICULA,CODFILIAL,PERLETIVO,
CODCUR,CODPER,CODTUN,CODTUR,NIS,TIPOLOGRADOURO,NACIONALIDADE,DATAENTRADA,
ORGAOEMISSOR,DATAINGRESSO,CURSOENSINOMEDIO,NECESPECIAIS,TIPONECESPECIAIS,
ALUNOCLASSECOMUM,APOIOPEDAGOGICO,CORRECAOFLUXO,BOLSAFAMILIA,TURMAUNIFICADA,
TURMAMULTI,TRANSPPUBLICO,TRANSPOFERECIDO,ZONARESIDENCIA,CONCLUINTE,
ADMITIDOCENSO,CEGUEIRA,BAIXAVISAO,SURDEZ,DEFICIENCIAAUDITIVA,SURDOCEGUEIRA,
DEFICIENCIAFISICA,DEFICIENCIAMENTAL,TRANSINVASDESENVOLV,SINDROMEDOWN,
DEFICIENCIAMULTIPLA,SUPERDOTADO,INEP)
SELECT CODCOLIGADA,MATRICULA,CODFILIAL,PERLETIVO,
CODCUR,CODPER,CODTUN,CODTUR,NIS,TIPOLOGRADOURO,NACIONALIDADE,DATAENTRADA,
ORGAOEMISSOR,DATAINGRESSO,CURSOENSINOMEDIO,NECESPECIAIS,TIPONECESPECIAIS,
ALUNOCLASSECOMUM,APOIOPEDAGOGICO,CORRECAOFLUXO,BOLSAFAMILIA,TURMAUNIFICADA,
TURMAMULTI,TRANSPPUBLICO,TRANSPOFERECIDO,ZONARESIDENCIA,CONCLUINTE,
ADMITIDOCENSO,CEGUEIRA,BAIXAVISAO,SURDEZ,DEFICIENCIAAUDITIVA,SURDOCEGUEIRA,
DEFICIENCIAFISICA,DEFICIENCIAMENTAL,TRANSINVASDESENVOLV,SINDROMEDOWN,
DEFICIENCIAMULTIPLA,SUPERDOTADO,INEP
FROM ZEALUNOSMEC_TEMP
GO

DROP TABLE ZEALUNOSMEC_TEMP
GO

