SELECT 
	DISTINCT
	CASE CLASS_PESSOA1
		WHEN 'Pai' THEN (SELECT NOME FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Mãe' THEN (SELECT NOME FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Responsável Financeiro' then (SELECT NOME FROM FCFO WHERE FCFO.CODCFO = PESSOA1)
		WHEN 'Responsável Acadêmico' then (SELECT NOME FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
	END AS PARENT1,
	CASE CLASS_PESSOA1
		WHEN 'Pai' THEN (SELECT P.DESCRICAO FROM PPESSOA JOIN PCODNACAO P ON P.CODCLIENTE=PPESSOA.NACIONALIDADE WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Mãe' THEN (SELECT P.DESCRICAO FROM PPESSOA JOIN PCODNACAO P ON P.CODCLIENTE=PPESSOA.NACIONALIDADE WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Responsável Financeiro' then (SELECT NOME FROM FCFO WHERE FCFO.CODCFO = PESSOA1)
		WHEN 'Responsável Acadêmico' then (SELECT P.DESCRICAO FROM PPESSOA JOIN PCODNACAO P ON P.CODCLIENTE=PPESSOA.NACIONALIDADE WHERE PPESSOA.CODIGO = PESSOA1)
	END AS NATIONALITY_PARENT1,
	CASE CLASS_PESSOA1
		WHEN 'Pai' THEN (SELECT EMAIL FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Mãe' THEN (SELECT EMAIL FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Responsável Financeiro' then (SELECT EMAIL FROM FCFO WHERE FCFO.CODCFO = PESSOA1)
		WHEN 'Responsável Acadêmico' then (SELECT EMAIL FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
	END AS EMAIL_PARENT1,
	CASE CLASS_PESSOA1
		WHEN 'Pai' THEN (SELECT TELEFONE1 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Mãe' THEN (SELECT TELEFONE1 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Responsável Financeiro' then (SELECT TELEFONE FROM FCFO WHERE FCFO.CODCFO = PESSOA1)
		WHEN 'Responsável Acadêmico' then (SELECT TELEFONE1 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
	END AS PHONE1_PARENT1,
	CASE CLASS_PESSOA1
		WHEN 'Pai' THEN (SELECT TELEFONE2 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Mãe' THEN (SELECT TELEFONE2 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
		WHEN 'Responsável Financeiro' then (SELECT TELEX FROM FCFO WHERE FCFO.CODCFO = PESSOA1)
		WHEN 'Responsável Acadêmico' then (SELECT TELEFONE2 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA1)
	END AS PHONE2_PARENT1,
	
	CASE CLASS_PESSOA2
		WHEN 'Pai' THEN (SELECT NOME FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Mãe' THEN (SELECT NOME FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Responsável Financeiro' then (SELECT NOME FROM FCFO WHERE FCFO.CODCFO = PESSOA2)
		WHEN 'Responsável Acadêmico' then (SELECT NOME FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
	END AS PARENT2,
	CASE CLASS_PESSOA2
		WHEN 'Pai' THEN (SELECT P.DESCRICAO FROM PPESSOA JOIN PCODNACAO P ON P.CODCLIENTE=PPESSOA.NACIONALIDADE WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Mãe' THEN (SELECT P.DESCRICAO FROM PPESSOA JOIN PCODNACAO P ON P.CODCLIENTE=PPESSOA.NACIONALIDADE WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Responsável Financeiro' then (SELECT NOME FROM FCFO WHERE FCFO.CODCFO = PESSOA2)
		WHEN 'Responsável Acadêmico' then (SELECT P.DESCRICAO FROM PPESSOA JOIN PCODNACAO P ON P.CODCLIENTE=PPESSOA.NACIONALIDADE WHERE PPESSOA.CODIGO = PESSOA2)
	END AS NATIONALITY_PARENT2,
	CASE CLASS_PESSOA2
		WHEN 'Pai' THEN (SELECT EMAIL FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Mãe' THEN (SELECT EMAIL FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Responsável Financeiro' then (SELECT EMAIL FROM FCFO WHERE FCFO.CODCFO = PESSOA2)
		WHEN 'Responsável Acadêmico' then (SELECT EMAIL FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
	END AS EMAIL_PARENT2,
	CASE CLASS_PESSOA2
		WHEN 'Pai' THEN (SELECT TELEFONE1 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Mãe' THEN (SELECT TELEFONE1 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Responsável Financeiro' then (SELECT TELEFONE FROM FCFO WHERE FCFO.CODCFO = PESSOA2)
		WHEN 'Responsável Acadêmico' then (SELECT TELEFONE1 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
	END AS PHONE1_PARENT2,
	CASE CLASS_PESSOA2
		WHEN 'Pai' THEN (SELECT TELEFONE2 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Mãe' THEN (SELECT TELEFONE2 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
		WHEN 'Responsável Financeiro' then (SELECT TELEX FROM FCFO WHERE FCFO.CODCFO = PESSOA2)
		WHEN 'Responsável Acadêmico' then (SELECT TELEFONE2 FROM PPESSOA WHERE PPESSOA.CODIGO = PESSOA2)
	END AS PHONE2_PARENT1
	 
FROM ZFAMILIA
WHERE PERLETIVO = '15/16'
AND STATUS in ('01','07')
