SELECT PFUNC.NOME, PCODNACAO.DESCRICAO ,PPESSOA.EMAIL, PPESSOA.TELEFONE1, PPESSOA.TELEFONE2 FROM PFUNC
join PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
join PCODNACAO on pcodnacao.CODCLIENTE = ppessoa.NACIONALIDADE
WHERE 
	PFUNC.CODSITUACAO = 'A' AND
	PFUNC.CODRECEBIMENTO = 'H' AND
	PPESSOA.NACIONALIDADE <> 10
	