/* valida informações */

SELECT 
	CPARTIDA.CREDITO, CPARTIDA.DEBITO, CPARTIDA.VALOR, CPARTIDA.DATA
FROM 
	CPARTIDA
WHERE 
	CPARTIDA.DATA >= '08-01-2016' AND CPARTIDA.DATA <= '08-31-2016'
--	AND CREDITO IS NOT NULL AND DEBITO IS NOT NULL
	AND CPARTIDA.CODHISTP NOT IN (SELECT CODHISTP FROM CHISTP WHERE CHISTP.HISTFECHA = 1)